# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laserYAGNd.ui'
#
# Created: Sat Oct 18 23:22:44 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Sans"))
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.input_title = QtGui.QLineEdit(self.centralwidget)
        self.input_title.setGeometry(QtCore.QRect(10, 20, 281, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 9, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.input_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_title.setFont(font)
        self.input_title.setFrame(False)
        self.input_title.setAlignment(QtCore.Qt.AlignCenter)
        self.input_title.setReadOnly(True)
        self.input_title.setObjectName(_fromUtf8("input_title"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 0, 991, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.input_parameter = QtGui.QToolBox(self.centralwidget)
        self.input_parameter.setGeometry(QtCore.QRect(10, 50, 281, 421))
        self.input_parameter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.input_parameter.setFrameShadow(QtGui.QFrame.Sunken)
        self.input_parameter.setLineWidth(1)
        self.input_parameter.setMidLineWidth(1)
        self.input_parameter.setObjectName(_fromUtf8("input_parameter"))
        self.times = QtGui.QWidget()
        self.times.setGeometry(QtCore.QRect(0, 0, 265, 249))
        self.times.setObjectName(_fromUtf8("times"))
        self.name1_times = QtGui.QLineEdit(self.times)
        self.name1_times.setGeometry(QtCore.QRect(0, 110, 261, 22))
        self.name1_times.setAlignment(QtCore.Qt.AlignCenter)
        self.name1_times.setReadOnly(True)
        self.name1_times.setObjectName(_fromUtf8("name1_times"))
        self.name_tau_g = QtGui.QLineEdit(self.times)
        self.name_tau_g.setGeometry(QtCore.QRect(90, 130, 61, 22))
        self.name_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.name_tau_g.setReadOnly(True)
        self.name_tau_g.setObjectName(_fromUtf8("name_tau_g"))
        self.value_tau_g = QtGui.QSpinBox(self.times)
        self.value_tau_g.setGeometry(QtCore.QRect(150, 130, 62, 22))
        self.value_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_g.setAccelerated(True)
        self.value_tau_g.setMaximum(1000)
        self.value_tau_g.setProperty("value", 230)
        self.value_tau_g.setObjectName(_fromUtf8("value_tau_g"))
        self.dim_tau_g = QtGui.QLineEdit(self.times)
        self.dim_tau_g.setGeometry(QtCore.QRect(210, 130, 51, 22))
        self.dim_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_g.setObjectName(_fromUtf8("dim_tau_g"))
        self.name2_times = QtGui.QLineEdit(self.times)
        self.name2_times.setGeometry(QtCore.QRect(0, 160, 261, 22))
        self.name2_times.setAlignment(QtCore.Qt.AlignCenter)
        self.name2_times.setReadOnly(True)
        self.name2_times.setObjectName(_fromUtf8("name2_times"))
        self.name_tau_a = QtGui.QLineEdit(self.times)
        self.name_tau_a.setGeometry(QtCore.QRect(90, 180, 61, 22))
        self.name_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.name_tau_a.setReadOnly(True)
        self.name_tau_a.setObjectName(_fromUtf8("name_tau_a"))
        self.dim_tau_a = QtGui.QLineEdit(self.times)
        self.dim_tau_a.setGeometry(QtCore.QRect(210, 180, 51, 22))
        self.dim_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_a.setReadOnly(True)
        self.dim_tau_a.setObjectName(_fromUtf8("dim_tau_a"))
        self.value_tau_a = QtGui.QDoubleSpinBox(self.times)
        self.value_tau_a.setGeometry(QtCore.QRect(150, 180, 62, 22))
        self.value_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_a.setMaximum(10.0)
        self.value_tau_a.setSingleStep(0.01)
        self.value_tau_a.setProperty("value", 3.5)
        self.value_tau_a.setObjectName(_fromUtf8("value_tau_a"))
        self.name1_calc_time = QtGui.QLineEdit(self.times)
        self.name1_calc_time.setGeometry(QtCore.QRect(0, 10, 261, 22))
        self.name1_calc_time.setAlignment(QtCore.Qt.AlignCenter)
        self.name1_calc_time.setReadOnly(True)
        self.name1_calc_time.setObjectName(_fromUtf8("name1_calc_time"))
        self.name_tau_m = QtGui.QLineEdit(self.times)
        self.name_tau_m.setGeometry(QtCore.QRect(90, 30, 61, 22))
        self.name_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.name_tau_m.setReadOnly(True)
        self.name_tau_m.setObjectName(_fromUtf8("name_tau_m"))
        self.dim_tau_m = QtGui.QLineEdit(self.times)
        self.dim_tau_m.setGeometry(QtCore.QRect(210, 30, 51, 22))
        self.dim_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_m.setObjectName(_fromUtf8("dim_tau_m"))
        self.value_tau_m = QtGui.QSpinBox(self.times)
        self.value_tau_m.setGeometry(QtCore.QRect(150, 30, 62, 22))
        self.value_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_m.setAccelerated(True)
        self.value_tau_m.setMaximum(100000)
        self.value_tau_m.setProperty("value", 50)
        self.value_tau_m.setObjectName(_fromUtf8("value_tau_m"))
        self.dim_dt = QtGui.QLineEdit(self.times)
        self.dim_dt.setGeometry(QtCore.QRect(210, 80, 51, 22))
        self.dim_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_dt.setObjectName(_fromUtf8("dim_dt"))
        self.value_dt = QtGui.QDoubleSpinBox(self.times)
        self.value_dt.setGeometry(QtCore.QRect(150, 80, 62, 22))
        self.value_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.value_dt.setAccelerated(True)
        self.value_dt.setDecimals(4)
        self.value_dt.setMaximum(1.0)
        self.value_dt.setSingleStep(0.0001)
        self.value_dt.setProperty("value", 0.01)
        self.value_dt.setObjectName(_fromUtf8("value_dt"))
        self.name_dt = QtGui.QLineEdit(self.times)
        self.name_dt.setGeometry(QtCore.QRect(90, 80, 61, 22))
        self.name_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.name_dt.setReadOnly(True)
        self.name_dt.setObjectName(_fromUtf8("name_dt"))
        self.name1_time_step = QtGui.QLineEdit(self.times)
        self.name1_time_step.setGeometry(QtCore.QRect(0, 60, 261, 22))
        self.name1_time_step.setAlignment(QtCore.Qt.AlignCenter)
        self.name1_time_step.setReadOnly(True)
        self.name1_time_step.setObjectName(_fromUtf8("name1_time_step"))
        self.input_parameter.addItem(self.times, _fromUtf8(""))
        self.dimentions = QtGui.QWidget()
        self.dimentions.setGeometry(QtCore.QRect(0, 0, 265, 249))
        self.dimentions.setObjectName(_fromUtf8("dimentions"))
        self.name_active_medium = QtGui.QLineEdit(self.dimentions)
        self.name_active_medium.setGeometry(QtCore.QRect(0, 0, 261, 22))
        self.name_active_medium.setAlignment(QtCore.Qt.AlignCenter)
        self.name_active_medium.setReadOnly(True)
        self.name_active_medium.setObjectName(_fromUtf8("name_active_medium"))
        self.name_lg = QtGui.QLineEdit(self.dimentions)
        self.name_lg.setGeometry(QtCore.QRect(110, 20, 51, 22))
        self.name_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lg.setReadOnly(True)
        self.name_lg.setObjectName(_fromUtf8("name_lg"))
        self.dim_lg = QtGui.QLineEdit(self.dimentions)
        self.dim_lg.setGeometry(QtCore.QRect(220, 20, 41, 22))
        self.dim_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_lg.setReadOnly(True)
        self.dim_lg.setObjectName(_fromUtf8("dim_lg"))
        self.value_lg = QtGui.QSpinBox(self.dimentions)
        self.value_lg.setGeometry(QtCore.QRect(160, 20, 61, 22))
        self.value_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.value_lg.setMaximum(10000)
        self.value_lg.setProperty("value", 1000)
        self.value_lg.setObjectName(_fromUtf8("value_lg"))
        self.dim_la = QtGui.QLineEdit(self.dimentions)
        self.dim_la.setGeometry(QtCore.QRect(220, 70, 41, 22))
        self.dim_la.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_la.setReadOnly(True)
        self.dim_la.setObjectName(_fromUtf8("dim_la"))
        self.name_la = QtGui.QLineEdit(self.dimentions)
        self.name_la.setGeometry(QtCore.QRect(110, 70, 51, 22))
        self.name_la.setAlignment(QtCore.Qt.AlignCenter)
        self.name_la.setReadOnly(True)
        self.name_la.setObjectName(_fromUtf8("name_la"))
        self.name_absorber = QtGui.QLineEdit(self.dimentions)
        self.name_absorber.setGeometry(QtCore.QRect(0, 50, 261, 22))
        self.name_absorber.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorber.setReadOnly(True)
        self.name_absorber.setObjectName(_fromUtf8("name_absorber"))
        self.value_la = QtGui.QSpinBox(self.dimentions)
        self.value_la.setGeometry(QtCore.QRect(160, 70, 61, 22))
        self.value_la.setAlignment(QtCore.Qt.AlignCenter)
        self.value_la.setMaximum(250)
        self.value_la.setProperty("value", 50)
        self.value_la.setObjectName(_fromUtf8("value_la"))
        self.name_rl = QtGui.QLineEdit(self.dimentions)
        self.name_rl.setGeometry(QtCore.QRect(110, 120, 51, 22))
        self.name_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rl.setReadOnly(True)
        self.name_rl.setObjectName(_fromUtf8("name_rl"))
        self.value_rl = QtGui.QSpinBox(self.dimentions)
        self.value_rl.setGeometry(QtCore.QRect(160, 120, 61, 22))
        self.value_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.value_rl.setMaximum(1000)
        self.value_rl.setProperty("value", 100)
        self.value_rl.setObjectName(_fromUtf8("value_rl"))
        self.dim_rl = QtGui.QLineEdit(self.dimentions)
        self.dim_rl.setGeometry(QtCore.QRect(220, 120, 41, 22))
        self.dim_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_rl.setReadOnly(True)
        self.dim_rl.setObjectName(_fromUtf8("dim_rl"))
        self.name_beam_radius = QtGui.QLineEdit(self.dimentions)
        self.name_beam_radius.setGeometry(QtCore.QRect(0, 100, 261, 22))
        self.name_beam_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.name_beam_radius.setReadOnly(True)
        self.name_beam_radius.setObjectName(_fromUtf8("name_beam_radius"))
        self.value_n = QtGui.QDoubleSpinBox(self.dimentions)
        self.value_n.setGeometry(QtCore.QRect(141, 170, 71, 22))
        self.value_n.setAlignment(QtCore.Qt.AlignCenter)
        self.value_n.setDecimals(4)
        self.value_n.setMinimum(1.0)
        self.value_n.setMaximum(5.0)
        self.value_n.setSingleStep(0.0001)
        self.value_n.setProperty("value", 1.8169)
        self.value_n.setObjectName(_fromUtf8("value_n"))
        self.name_index = QtGui.QLineEdit(self.dimentions)
        self.name_index.setGeometry(QtCore.QRect(0, 150, 261, 22))
        self.name_index.setAlignment(QtCore.Qt.AlignCenter)
        self.name_index.setReadOnly(True)
        self.name_index.setObjectName(_fromUtf8("name_index"))
        self.name_n = QtGui.QLineEdit(self.dimentions)
        self.name_n.setGeometry(QtCore.QRect(90, 170, 51, 22))
        self.name_n.setAlignment(QtCore.Qt.AlignCenter)
        self.name_n.setReadOnly(True)
        self.name_n.setObjectName(_fromUtf8("name_n"))
        self.dim_n = QtGui.QLineEdit(self.dimentions)
        self.dim_n.setGeometry(QtCore.QRect(210, 170, 51, 22))
        self.dim_n.setText(_fromUtf8(""))
        self.dim_n.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_n.setReadOnly(True)
        self.dim_n.setObjectName(_fromUtf8("dim_n"))
        self.input_parameter.addItem(self.dimentions, _fromUtf8(""))
        self.crosssections = QtGui.QWidget()
        self.crosssections.setObjectName(_fromUtf8("crosssections"))
        self.name_laser_trans = QtGui.QLineEdit(self.crosssections)
        self.name_laser_trans.setGeometry(QtCore.QRect(0, 0, 261, 22))
        self.name_laser_trans.setAlignment(QtCore.Qt.AlignCenter)
        self.name_laser_trans.setReadOnly(True)
        self.name_laser_trans.setObjectName(_fromUtf8("name_laser_trans"))
        self.name_sigma_g = QtGui.QLineEdit(self.crosssections)
        self.name_sigma_g.setGeometry(QtCore.QRect(40, 20, 71, 22))
        self.name_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.name_sigma_g.setReadOnly(True)
        self.name_sigma_g.setObjectName(_fromUtf8("name_sigma_g"))
        self.value_sigma_g = QtGui.QDoubleSpinBox(self.crosssections)
        self.value_sigma_g.setGeometry(QtCore.QRect(110, 20, 61, 22))
        self.value_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_g.setMaximum(5.0)
        self.value_sigma_g.setSingleStep(0.01)
        self.value_sigma_g.setProperty("value", 3.5)
        self.value_sigma_g.setObjectName(_fromUtf8("value_sigma_g"))
        self.dim_sigma_g = QtGui.QLineEdit(self.crosssections)
        self.dim_sigma_g.setGeometry(QtCore.QRect(170, 20, 91, 22))
        self.dim_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_g.setReadOnly(True)
        self.dim_sigma_g.setObjectName(_fromUtf8("dim_sigma_g"))
        self.dim_sigma_a1 = QtGui.QLineEdit(self.crosssections)
        self.dim_sigma_a1.setGeometry(QtCore.QRect(170, 70, 91, 22))
        self.dim_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_a1.setReadOnly(True)
        self.dim_sigma_a1.setObjectName(_fromUtf8("dim_sigma_a1"))
        self.name_absorber_levels_1 = QtGui.QLineEdit(self.crosssections)
        self.name_absorber_levels_1.setGeometry(QtCore.QRect(0, 50, 261, 22))
        self.name_absorber_levels_1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorber_levels_1.setReadOnly(True)
        self.name_absorber_levels_1.setObjectName(_fromUtf8("name_absorber_levels_1"))
        self.name_sigma_a1 = QtGui.QLineEdit(self.crosssections)
        self.name_sigma_a1.setGeometry(QtCore.QRect(40, 70, 71, 22))
        self.name_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_sigma_a1.setReadOnly(True)
        self.name_sigma_a1.setObjectName(_fromUtf8("name_sigma_a1"))
        self.value_sigma_a1 = QtGui.QDoubleSpinBox(self.crosssections)
        self.value_sigma_a1.setGeometry(QtCore.QRect(110, 70, 61, 22))
        self.value_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_a1.setMaximum(5.0)
        self.value_sigma_a1.setSingleStep(0.01)
        self.value_sigma_a1.setProperty("value", 2.4)
        self.value_sigma_a1.setObjectName(_fromUtf8("value_sigma_a1"))
        self.dim_sigma_a2 = QtGui.QLineEdit(self.crosssections)
        self.dim_sigma_a2.setGeometry(QtCore.QRect(170, 120, 91, 22))
        self.dim_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_a2.setReadOnly(True)
        self.dim_sigma_a2.setObjectName(_fromUtf8("dim_sigma_a2"))
        self.name_sigma_a2 = QtGui.QLineEdit(self.crosssections)
        self.name_sigma_a2.setGeometry(QtCore.QRect(40, 120, 71, 22))
        self.name_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_sigma_a2.setReadOnly(True)
        self.name_sigma_a2.setObjectName(_fromUtf8("name_sigma_a2"))
        self.name_absorber_levels_2 = QtGui.QLineEdit(self.crosssections)
        self.name_absorber_levels_2.setGeometry(QtCore.QRect(0, 100, 261, 22))
        self.name_absorber_levels_2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorber_levels_2.setReadOnly(True)
        self.name_absorber_levels_2.setObjectName(_fromUtf8("name_absorber_levels_2"))
        self.value_sigma_a2 = QtGui.QDoubleSpinBox(self.crosssections)
        self.value_sigma_a2.setGeometry(QtCore.QRect(110, 120, 61, 22))
        self.value_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_a2.setMaximum(5.0)
        self.value_sigma_a2.setSingleStep(0.01)
        self.value_sigma_a2.setProperty("value", 2.8)
        self.value_sigma_a2.setObjectName(_fromUtf8("value_sigma_a2"))
        self.input_parameter.addItem(self.crosssections, _fromUtf8(""))
        self.concentrations = QtGui.QWidget()
        self.concentrations.setObjectName(_fromUtf8("concentrations"))
        self.name_activator_conc = QtGui.QLineEdit(self.concentrations)
        self.name_activator_conc.setGeometry(QtCore.QRect(0, 0, 261, 22))
        self.name_activator_conc.setAlignment(QtCore.Qt.AlignCenter)
        self.name_activator_conc.setReadOnly(True)
        self.name_activator_conc.setObjectName(_fromUtf8("name_activator_conc"))
        self.name_Ng = QtGui.QLineEdit(self.concentrations)
        self.name_Ng.setGeometry(QtCore.QRect(40, 20, 61, 22))
        self.name_Ng.setAlignment(QtCore.Qt.AlignCenter)
        self.name_Ng.setReadOnly(True)
        self.name_Ng.setObjectName(_fromUtf8("name_Ng"))
        self.value_Ng = QtGui.QDoubleSpinBox(self.concentrations)
        self.value_Ng.setGeometry(QtCore.QRect(100, 20, 62, 22))
        self.value_Ng.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Ng.setMinimum(0.0)
        self.value_Ng.setMaximum(1000.0)
        self.value_Ng.setSingleStep(0.01)
        self.value_Ng.setProperty("value", 1.66)
        self.value_Ng.setObjectName(_fromUtf8("value_Ng"))
        self.dim_Ng = QtGui.QLineEdit(self.concentrations)
        self.dim_Ng.setGeometry(QtCore.QRect(160, 20, 101, 22))
        self.dim_Ng.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Ng.setReadOnly(True)
        self.dim_Ng.setObjectName(_fromUtf8("dim_Ng"))
        self.dim_Ng_proc = QtGui.QLineEdit(self.concentrations)
        self.dim_Ng_proc.setGeometry(QtCore.QRect(160, 70, 101, 22))
        self.dim_Ng_proc.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Ng_proc.setReadOnly(True)
        self.dim_Ng_proc.setObjectName(_fromUtf8("dim_Ng_proc"))
        self.value_Ng_proc = QtGui.QDoubleSpinBox(self.concentrations)
        self.value_Ng_proc.setGeometry(QtCore.QRect(100, 70, 62, 22))
        self.value_Ng_proc.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Ng_proc.setMaximum(10.0)
        self.value_Ng_proc.setSingleStep(0.01)
        self.value_Ng_proc.setProperty("value", 1.2)
        self.value_Ng_proc.setObjectName(_fromUtf8("value_Ng_proc"))
        self.name_activator_conc_proc = QtGui.QLineEdit(self.concentrations)
        self.name_activator_conc_proc.setGeometry(QtCore.QRect(0, 50, 261, 22))
        self.name_activator_conc_proc.setAlignment(QtCore.Qt.AlignCenter)
        self.name_activator_conc_proc.setReadOnly(True)
        self.name_activator_conc_proc.setObjectName(_fromUtf8("name_activator_conc_proc"))
        self.name_Ng_proc = QtGui.QLineEdit(self.concentrations)
        self.name_Ng_proc.setGeometry(QtCore.QRect(40, 70, 61, 22))
        self.name_Ng_proc.setAlignment(QtCore.Qt.AlignCenter)
        self.name_Ng_proc.setReadOnly(True)
        self.name_Ng_proc.setObjectName(_fromUtf8("name_Ng_proc"))
        self.name_cr_conc = QtGui.QLineEdit(self.concentrations)
        self.name_cr_conc.setGeometry(QtCore.QRect(0, 100, 261, 22))
        self.name_cr_conc.setAlignment(QtCore.Qt.AlignCenter)
        self.name_cr_conc.setObjectName(_fromUtf8("name_cr_conc"))
        self.value_Na = QtGui.QDoubleSpinBox(self.concentrations)
        self.value_Na.setGeometry(QtCore.QRect(100, 120, 62, 22))
        self.value_Na.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Na.setMaximum(1000.0)
        self.value_Na.setSingleStep(0.01)
        self.value_Na.setProperty("value", 1.0)
        self.value_Na.setObjectName(_fromUtf8("value_Na"))
        self.dim_Na = QtGui.QLineEdit(self.concentrations)
        self.dim_Na.setGeometry(QtCore.QRect(160, 120, 101, 22))
        self.dim_Na.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Na.setReadOnly(True)
        self.dim_Na.setObjectName(_fromUtf8("dim_Na"))
        self.name_Na = QtGui.QLineEdit(self.concentrations)
        self.name_Na.setGeometry(QtCore.QRect(40, 120, 61, 22))
        self.name_Na.setAlignment(QtCore.Qt.AlignCenter)
        self.name_Na.setReadOnly(True)
        self.name_Na.setObjectName(_fromUtf8("name_Na"))
        self.input_parameter.addItem(self.concentrations, _fromUtf8(""))
        self.losses = QtGui.QWidget()
        self.losses.setObjectName(_fromUtf8("losses"))
        self.name_absorbtion_coef = QtGui.QLineEdit(self.losses)
        self.name_absorbtion_coef.setGeometry(QtCore.QRect(0, 0, 261, 22))
        self.name_absorbtion_coef.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorbtion_coef.setReadOnly(True)
        self.name_absorbtion_coef.setObjectName(_fromUtf8("name_absorbtion_coef"))
        self.name_alpha_p = QtGui.QLineEdit(self.losses)
        self.name_alpha_p.setGeometry(QtCore.QRect(30, 20, 81, 22))
        self.name_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.name_alpha_p.setObjectName(_fromUtf8("name_alpha_p"))
        self.value_alpha_p = QtGui.QDoubleSpinBox(self.losses)
        self.value_alpha_p.setGeometry(QtCore.QRect(110, 20, 62, 22))
        self.value_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.value_alpha_p.setDecimals(0)
        self.value_alpha_p.setProperty("value", 5.0)
        self.value_alpha_p.setObjectName(_fromUtf8("value_alpha_p"))
        self.dim_alpha_p = QtGui.QLineEdit(self.losses)
        self.dim_alpha_p.setGeometry(QtCore.QRect(170, 20, 91, 22))
        self.dim_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_alpha_p.setReadOnly(True)
        self.dim_alpha_p.setObjectName(_fromUtf8("dim_alpha_p"))
        self.dim_R1 = QtGui.QLineEdit(self.losses)
        self.dim_R1.setGeometry(QtCore.QRect(190, 70, 71, 22))
        self.dim_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_R1.setReadOnly(True)
        self.dim_R1.setObjectName(_fromUtf8("dim_R1"))
        self.value_R1 = QtGui.QDoubleSpinBox(self.losses)
        self.value_R1.setGeometry(QtCore.QRect(130, 70, 62, 22))
        self.value_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_R1.setMaximum(1.0)
        self.value_R1.setSingleStep(0.01)
        self.value_R1.setProperty("value", 1.0)
        self.value_R1.setObjectName(_fromUtf8("value_R1"))
        self.name_R1 = QtGui.QLineEdit(self.losses)
        self.name_R1.setGeometry(QtCore.QRect(52, 70, 81, 22))
        self.name_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_R1.setReadOnly(True)
        self.name_R1.setObjectName(_fromUtf8("name_R1"))
        self.name_input_mirror = QtGui.QLineEdit(self.losses)
        self.name_input_mirror.setGeometry(QtCore.QRect(0, 50, 261, 22))
        self.name_input_mirror.setAlignment(QtCore.Qt.AlignCenter)
        self.name_input_mirror.setReadOnly(True)
        self.name_input_mirror.setObjectName(_fromUtf8("name_input_mirror"))
        self.dim_R2 = QtGui.QLineEdit(self.losses)
        self.dim_R2.setGeometry(QtCore.QRect(190, 120, 71, 22))
        self.dim_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_R2.setReadOnly(True)
        self.dim_R2.setObjectName(_fromUtf8("dim_R2"))
        self.value_R2 = QtGui.QDoubleSpinBox(self.losses)
        self.value_R2.setGeometry(QtCore.QRect(130, 120, 62, 22))
        self.value_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_R2.setMaximum(1.0)
        self.value_R2.setSingleStep(0.01)
        self.value_R2.setProperty("value", 0.99)
        self.value_R2.setObjectName(_fromUtf8("value_R2"))
        self.name_R2 = QtGui.QLineEdit(self.losses)
        self.name_R2.setGeometry(QtCore.QRect(52, 120, 81, 22))
        self.name_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_R2.setReadOnly(True)
        self.name_R2.setObjectName(_fromUtf8("name_R2"))
        self.name_output_mirror = QtGui.QLineEdit(self.losses)
        self.name_output_mirror.setGeometry(QtCore.QRect(0, 100, 261, 22))
        self.name_output_mirror.setAlignment(QtCore.Qt.AlignCenter)
        self.name_output_mirror.setReadOnly(True)
        self.name_output_mirror.setObjectName(_fromUtf8("name_output_mirror"))
        self.input_parameter.addItem(self.losses, _fromUtf8(""))
        self.pumping = QtGui.QWidget()
        self.pumping.setObjectName(_fromUtf8("pumping"))
        self.name_pump_power = QtGui.QLineEdit(self.pumping)
        self.name_pump_power.setGeometry(QtCore.QRect(0, 10, 261, 22))
        self.name_pump_power.setAlignment(QtCore.Qt.AlignCenter)
        self.name_pump_power.setReadOnly(True)
        self.name_pump_power.setObjectName(_fromUtf8("name_pump_power"))
        self.name_Pi = QtGui.QLineEdit(self.pumping)
        self.name_Pi.setGeometry(QtCore.QRect(92, 30, 61, 22))
        self.name_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.name_Pi.setReadOnly(True)
        self.name_Pi.setObjectName(_fromUtf8("name_Pi"))
        self.value_Pi = QtGui.QDoubleSpinBox(self.pumping)
        self.value_Pi.setGeometry(QtCore.QRect(150, 30, 62, 22))
        self.value_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Pi.setAccelerated(True)
        self.value_Pi.setMaximum(100.0)
        self.value_Pi.setSingleStep(0.01)
        self.value_Pi.setProperty("value", 0.2)
        self.value_Pi.setObjectName(_fromUtf8("value_Pi"))
        self.dim_Pi = QtGui.QLineEdit(self.pumping)
        self.dim_Pi.setGeometry(QtCore.QRect(210, 30, 51, 22))
        self.dim_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Pi.setReadOnly(True)
        self.dim_Pi.setObjectName(_fromUtf8("dim_Pi"))
        self.dim_wavelength = QtGui.QLineEdit(self.pumping)
        self.dim_wavelength.setGeometry(QtCore.QRect(210, 80, 51, 22))
        self.dim_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_wavelength.setReadOnly(True)
        self.dim_wavelength.setObjectName(_fromUtf8("dim_wavelength"))
        self.value_wavelength = QtGui.QDoubleSpinBox(self.pumping)
        self.value_wavelength.setGeometry(QtCore.QRect(141, 80, 71, 22))
        self.value_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.value_wavelength.setDecimals(3)
        self.value_wavelength.setMaximum(5.0)
        self.value_wavelength.setSingleStep(0.01)
        self.value_wavelength.setProperty("value", 0.808)
        self.value_wavelength.setObjectName(_fromUtf8("value_wavelength"))
        self.name_pump_wavelength = QtGui.QLineEdit(self.pumping)
        self.name_pump_wavelength.setGeometry(QtCore.QRect(0, 60, 261, 22))
        self.name_pump_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.name_pump_wavelength.setReadOnly(True)
        self.name_pump_wavelength.setObjectName(_fromUtf8("name_pump_wavelength"))
        self.name_wavelength = QtGui.QLineEdit(self.pumping)
        self.name_wavelength.setGeometry(QtCore.QRect(60, 80, 81, 22))
        self.name_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.name_wavelength.setReadOnly(True)
        self.name_wavelength.setObjectName(_fromUtf8("name_wavelength"))
        self.value_rp = QtGui.QSpinBox(self.pumping)
        self.value_rp.setGeometry(QtCore.QRect(160, 130, 61, 22))
        self.value_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.value_rp.setMaximum(1000)
        self.value_rp.setProperty("value", 300)
        self.value_rp.setObjectName(_fromUtf8("value_rp"))
        self.dim_rp = QtGui.QLineEdit(self.pumping)
        self.dim_rp.setGeometry(QtCore.QRect(220, 130, 41, 22))
        self.dim_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_rp.setReadOnly(True)
        self.dim_rp.setObjectName(_fromUtf8("dim_rp"))
        self.name_pump_radius = QtGui.QLineEdit(self.pumping)
        self.name_pump_radius.setGeometry(QtCore.QRect(0, 110, 261, 22))
        self.name_pump_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.name_pump_radius.setReadOnly(True)
        self.name_pump_radius.setObjectName(_fromUtf8("name_pump_radius"))
        self.name_rp = QtGui.QLineEdit(self.pumping)
        self.name_rp.setGeometry(QtCore.QRect(110, 130, 51, 22))
        self.name_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rp.setReadOnly(True)
        self.name_rp.setObjectName(_fromUtf8("name_rp"))
        self.input_parameter.addItem(self.pumping, _fromUtf8(""))
        self.button_quit = QtGui.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(670, 530, 99, 23))
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.button_calculate = QtGui.QPushButton(self.centralwidget)
        self.button_calculate.setGeometry(QtCore.QRect(50, 490, 211, 23))
        self.button_calculate.setCheckable(False)
        self.button_calculate.setObjectName(_fromUtf8("button_calculate"))
        self.plot_ndna = QtGui.QFrame(self.centralwidget)
        self.plot_ndna.setGeometry(QtCore.QRect(300, 20, 491, 241))
        self.plot_ndna.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_ndna.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_ndna.setObjectName(_fromUtf8("plot_ndna"))
        self.plot_P = QtGui.QFrame(self.centralwidget)
        self.plot_P.setGeometry(QtCore.QRect(300, 270, 491, 231))
        self.plot_P.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_P.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_P.setObjectName(_fromUtf8("plot_P"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_config = QtGui.QAction(MainWindow)
        self.actionOpen_config.setObjectName(_fromUtf8("actionOpen_config"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave_config = QtGui.QAction(MainWindow)
        self.actionSave_config.setObjectName(_fromUtf8("actionSave_config"))
        self.actionQuit_2 = QtGui.QAction(MainWindow)
        self.actionQuit_2.setObjectName(_fromUtf8("actionQuit_2"))
        self.menuFile.addAction(self.actionOpen_config)
        self.menuFile.addAction(self.actionSave_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.input_parameter.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_quit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.actionQuit_2, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Nd:YAG Laser", None))
        self.input_title.setText(_translate("MainWindow", "Input Parameters", None))
        self.name1_times.setText(_translate("MainWindow", "Lifetime of high laser level", None))
        self.name_tau_g.setText(_translate("MainWindow", "tau_g ", None))
        self.dim_tau_g.setText(_translate("MainWindow", "μs", None))
        self.name2_times.setText(_translate("MainWindow", "Lifetime of Cr(4+) excited level", None))
        self.name_tau_a.setText(_translate("MainWindow", "tau_a", None))
        self.dim_tau_a.setText(_translate("MainWindow", "μs", None))
        self.name1_calc_time.setText(_translate("MainWindow", "Calculation time", None))
        self.name_tau_m.setText(_translate("MainWindow", "tau_m", None))
        self.dim_tau_m.setText(_translate("MainWindow", "μs", None))
        self.dim_dt.setText(_translate("MainWindow", "μs", None))
        self.name_dt.setText(_translate("MainWindow", "dt", None))
        self.name1_time_step.setText(_translate("MainWindow", "Time spem in calculations", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.times), _translate("MainWindow", "Times", None))
        self.name_active_medium.setText(_translate("MainWindow", "Thickness of active medium", None))
        self.name_lg.setText(_translate("MainWindow", "lg", None))
        self.dim_lg.setText(_translate("MainWindow", "μm", None))
        self.dim_la.setText(_translate("MainWindow", "μm", None))
        self.name_la.setText(_translate("MainWindow", "la", None))
        self.name_absorber.setText(_translate("MainWindow", "Absorber thickness", None))
        self.name_rl.setText(_translate("MainWindow", "rl", None))
        self.dim_rl.setText(_translate("MainWindow", "μm", None))
        self.name_beam_radius.setText(_translate("MainWindow", "Laser beam radius", None))
        self.name_index.setText(_translate("MainWindow", "YAG:Nd refractive index at 1.064 um", None))
        self.name_n.setText(_translate("MainWindow", "n", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.dimentions), _translate("MainWindow", "Dimentions", None))
        self.name_laser_trans.setText(_translate("MainWindow", "Efficient cross-section of laser transition", None))
        self.name_sigma_g.setText(_translate("MainWindow", "sigma_g", None))
        self.dim_sigma_g.setText(_translate("MainWindow", "*10^-11 μm^2", None))
        self.dim_sigma_a1.setText(_translate("MainWindow", "*10^-10 μm^2", None))
        self.name_absorber_levels_1.setText(_translate("MainWindow", "Cross-section  between Cr(4+) levels", None))
        self.name_sigma_a1.setText(_translate("MainWindow", "sigma_a1", None))
        self.dim_sigma_a2.setText(_translate("MainWindow", "*10^-11 μm^2", None))
        self.name_sigma_a2.setText(_translate("MainWindow", "sigma_a2", None))
        self.name_absorber_levels_2.setText(_translate("MainWindow", "Cross-section  between Cr(4+) levels", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.crosssections), _translate("MainWindow", "Cross-sections", None))
        self.name_activator_conc.setText(_translate("MainWindow", "Activator concentration", None))
        self.name_Ng.setText(_translate("MainWindow", "Ng", None))
        self.dim_Ng.setText(_translate("MainWindow", "*10^5 μm^-3", None))
        self.dim_Ng_proc.setText(_translate("MainWindow", "%", None))
        self.name_activator_conc_proc.setText(_translate("MainWindow", "Activator concentration at %", None))
        self.name_Ng_proc.setText(_translate("MainWindow", "Ng", None))
        self.name_cr_conc.setText(_translate("MainWindow", "Cr(4+) ion concentration", None))
        self.dim_Na.setText(_translate("MainWindow", "*10^5 μm^-3", None))
        self.name_Na.setText(_translate("MainWindow", "Na", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.concentrations), _translate("MainWindow", "Concentrations", None))
        self.name_absorbtion_coef.setText(_translate("MainWindow", "Absorption coefficient on the wavelength", None))
        self.name_alpha_p.setText(_translate("MainWindow", "alpha_p", None))
        self.dim_alpha_p.setText(_translate("MainWindow", "*10^-7 1/μm", None))
        self.name_R1.setText(_translate("MainWindow", "R1", None))
        self.name_input_mirror.setText(_translate("MainWindow", "Reflectivity of input mirror", None))
        self.name_R2.setText(_translate("MainWindow", "R2", None))
        self.name_output_mirror.setText(_translate("MainWindow", "Reflectivity of output mirror", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.losses), _translate("MainWindow", "Losses", None))
        self.name_pump_power.setText(_translate("MainWindow", "Pumping power", None))
        self.name_Pi.setText(_translate("MainWindow", "Pi", None))
        self.dim_Pi.setText(_translate("MainWindow", "W", None))
        self.dim_wavelength.setText(_translate("MainWindow", "μm", None))
        self.name_pump_wavelength.setText(_translate("MainWindow", "Pumping wavelength", None))
        self.name_wavelength.setText(_translate("MainWindow", "wavelenght", None))
        self.dim_rp.setText(_translate("MainWindow", "μm", None))
        self.name_pump_radius.setText(_translate("MainWindow", "Pumping beam radius", None))
        self.name_rp.setText(_translate("MainWindow", "rp", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.pumping), _translate("MainWindow", "Pumping", None))
        self.button_quit.setText(_translate("MainWindow", "Quit", None))
        self.button_calculate.setText(_translate("MainWindow", "Calculate", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_config.setText(_translate("MainWindow", "Open config", None))
        self.actionOpen_config.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSave_config.setText(_translate("MainWindow", "Save config", None))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

