# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laserYAGNd.ui'
#
# Created: Mon Oct 27 14:45:03 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import scientificspin as scspin

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName(_fromUtf8("mainwindow"))
        mainwindow.resize(1024, 768)
        mainwindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(mainwindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Sans"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(2, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(2, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(2, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 2, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.plot_ndna = QtGui.QFrame(self.centralwidget)
        self.plot_ndna.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_ndna.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_ndna.setObjectName(_fromUtf8("plot_ndna"))
        self.gridLayout.addWidget(self.plot_ndna, 1, 2, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(275, 2, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 0, 1, 2)
        self.button_quit = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_quit.setFont(font)
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.gridLayout.addWidget(self.button_quit, 3, 4, 1, 1)
        self.plot_P = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_P.sizePolicy().hasHeightForWidth())
        self.plot_P.setSizePolicy(sizePolicy)
        self.plot_P.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_P.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_P.setObjectName(_fromUtf8("plot_P"))
        self.gridLayout.addWidget(self.plot_P, 2, 2, 1, 3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.button_calculate = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_calculate.setFont(font)
        self.button_calculate.setCheckable(False)
        self.button_calculate.setObjectName(_fromUtf8("button_calculate"))
        self.gridLayout_2.addWidget(self.button_calculate, 2, 0, 1, 1)
        self.name_input_param = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.name_input_param.setFont(font)
        self.name_input_param.setAlignment(QtCore.Qt.AlignCenter)
        self.name_input_param.setObjectName(_fromUtf8("name_input_param"))
        self.gridLayout_2.addWidget(self.name_input_param, 0, 0, 1, 1)
        self.input_parameter = QtGui.QToolBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_parameter.sizePolicy().hasHeightForWidth())
        self.input_parameter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.input_parameter.setFont(font)
        self.input_parameter.setAutoFillBackground(False)
        self.input_parameter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.input_parameter.setFrameShadow(QtGui.QFrame.Sunken)
        self.input_parameter.setLineWidth(1)
        self.input_parameter.setMidLineWidth(1)
        self.input_parameter.setObjectName(_fromUtf8("input_parameter"))
        self.times = QtGui.QWidget()
        self.times.setGeometry(QtCore.QRect(0, 0, 263, 379))
        self.times.setObjectName(_fromUtf8("times"))
        self.value_tau_g = QtGui.QSpinBox(self.times)
        self.value_tau_g.setGeometry(QtCore.QRect(170, 155, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_tau_g.setFont(font)
        self.value_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_g.setAccelerated(True)
        self.value_tau_g.setSuffix(_fromUtf8(""))
        self.value_tau_g.setPrefix(_fromUtf8(""))
        self.value_tau_g.setMaximum(1000)
        self.value_tau_g.setProperty("value", 230)
        self.value_tau_g.setObjectName(_fromUtf8("value_tau_g"))
        self.value_tau_a = QtGui.QDoubleSpinBox(self.times)
        self.value_tau_a.setGeometry(QtCore.QRect(170, 215, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_tau_a.setFont(font)
        self.value_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_a.setAccelerated(True)
        self.value_tau_a.setPrefix(_fromUtf8(""))
        self.value_tau_a.setSuffix(_fromUtf8(""))
        self.value_tau_a.setMaximum(10.0)
        self.value_tau_a.setSingleStep(0.01)
        self.value_tau_a.setProperty("value", 3.5)
        self.value_tau_a.setObjectName(_fromUtf8("value_tau_a"))
        self.value_tau_m = QtGui.QSpinBox(self.times)
        self.value_tau_m.setGeometry(QtCore.QRect(170, 35, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.value_tau_m.setFont(font)
        self.value_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_m.setAccelerated(True)
        self.value_tau_m.setSuffix(_fromUtf8(""))
        self.value_tau_m.setPrefix(_fromUtf8(""))
        self.value_tau_m.setMaximum(100000)
        self.value_tau_m.setProperty("value", 50)
        self.value_tau_m.setObjectName(_fromUtf8("value_tau_m"))
        self.value_dt = QtGui.QDoubleSpinBox(self.times)
        self.value_dt.setGeometry(QtCore.QRect(170, 95, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_dt.setFont(font)
        self.value_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.value_dt.setAccelerated(True)
        self.value_dt.setPrefix(_fromUtf8(""))
        self.value_dt.setSuffix(_fromUtf8(""))
        self.value_dt.setDecimals(3)
        self.value_dt.setMaximum(1.0)
        self.value_dt.setSingleStep(0.001)
        self.value_dt.setProperty("value", 0.01)
        self.value_dt.setObjectName(_fromUtf8("value_dt"))
        self.name_calc_time = QtGui.QLabel(self.times)
        self.name_calc_time.setGeometry(QtCore.QRect(0, 10, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_calc_time.setFont(font)
        self.name_calc_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_calc_time.setObjectName(_fromUtf8("name_calc_time"))
        self.name_tau_m = QtGui.QLabel(self.times)
        self.name_tau_m.setGeometry(QtCore.QRect(110, 35, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_tau_m.setFont(font)
        self.name_tau_m.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_tau_m.setObjectName(_fromUtf8("name_tau_m"))
        self.dim_tau_m = QtGui.QLabel(self.times)
        self.dim_tau_m.setGeometry(QtCore.QRect(230, 35, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_tau_m.setFont(font)
        self.dim_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_m.setObjectName(_fromUtf8("dim_tau_m"))
        self.name_calc_step = QtGui.QLabel(self.times)
        self.name_calc_step.setGeometry(QtCore.QRect(0, 70, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setUnderline(True)
        self.name_calc_step.setFont(font)
        self.name_calc_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_calc_step.setObjectName(_fromUtf8("name_calc_step"))
        self.name_dt_2 = QtGui.QLabel(self.times)
        self.name_dt_2.setGeometry(QtCore.QRect(110, 95, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_dt_2.setFont(font)
        self.name_dt_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_dt_2.setObjectName(_fromUtf8("name_dt_2"))
        self.dim_dt_2 = QtGui.QLabel(self.times)
        self.dim_dt_2.setGeometry(QtCore.QRect(230, 95, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_dt_2.setFont(font)
        self.dim_dt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_dt_2.setObjectName(_fromUtf8("dim_dt_2"))
        self.dim_tau_g = QtGui.QLabel(self.times)
        self.dim_tau_g.setGeometry(QtCore.QRect(230, 155, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_tau_g.setFont(font)
        self.dim_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_g.setObjectName(_fromUtf8("dim_tau_g"))
        self.name_tau_g = QtGui.QLabel(self.times)
        self.name_tau_g.setGeometry(QtCore.QRect(110, 155, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_tau_g.setFont(font)
        self.name_tau_g.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_tau_g.setObjectName(_fromUtf8("name_tau_g"))
        self.name_high_level = QtGui.QLabel(self.times)
        self.name_high_level.setGeometry(QtCore.QRect(0, 130, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setUnderline(True)
        self.name_high_level.setFont(font)
        self.name_high_level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_high_level.setObjectName(_fromUtf8("name_high_level"))
        self.dim_tau_a = QtGui.QLabel(self.times)
        self.dim_tau_a.setGeometry(QtCore.QRect(230, 215, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_tau_a.setFont(font)
        self.dim_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_a.setObjectName(_fromUtf8("dim_tau_a"))
        self.name_cr_level = QtGui.QLabel(self.times)
        self.name_cr_level.setGeometry(QtCore.QRect(0, 190, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setUnderline(True)
        self.name_cr_level.setFont(font)
        self.name_cr_level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_cr_level.setObjectName(_fromUtf8("name_cr_level"))
        self.name_tau_a = QtGui.QLabel(self.times)
        self.name_tau_a.setGeometry(QtCore.QRect(110, 215, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_tau_a.setFont(font)
        self.name_tau_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_tau_a.setObjectName(_fromUtf8("name_tau_a"))
        self.input_parameter.addItem(self.times, _fromUtf8(""))
        self.resonator = QtGui.QWidget()
        self.resonator.setGeometry(QtCore.QRect(0, 0, 263, 379))
        self.resonator.setObjectName(_fromUtf8("resonator"))
        self.value_lg = QtGui.QSpinBox(self.resonator)
        self.value_lg.setGeometry(QtCore.QRect(170, 25, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_lg.setFont(font)
        self.value_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.value_lg.setAccelerated(True)
        self.value_lg.setSuffix(_fromUtf8(""))
        self.value_lg.setPrefix(_fromUtf8(""))
        self.value_lg.setMaximum(10000)
        self.value_lg.setProperty("value", 1000)
        self.value_lg.setObjectName(_fromUtf8("value_lg"))
        self.value_la = QtGui.QSpinBox(self.resonator)
        self.value_la.setGeometry(QtCore.QRect(170, 80, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_la.setFont(font)
        self.value_la.setAlignment(QtCore.Qt.AlignCenter)
        self.value_la.setAccelerated(True)
        self.value_la.setSuffix(_fromUtf8(""))
        self.value_la.setPrefix(_fromUtf8(""))
        self.value_la.setMaximum(250)
        self.value_la.setProperty("value", 50)
        self.value_la.setObjectName(_fromUtf8("value_la"))
        self.value_rl = QtGui.QSpinBox(self.resonator)
        self.value_rl.setGeometry(QtCore.QRect(170, 135, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_rl.setFont(font)
        self.value_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.value_rl.setAccelerated(True)
        self.value_rl.setSuffix(_fromUtf8(""))
        self.value_rl.setPrefix(_fromUtf8(""))
        self.value_rl.setMaximum(1000)
        self.value_rl.setProperty("value", 300)
        self.value_rl.setObjectName(_fromUtf8("value_rl"))
        self.dim_lg = QtGui.QLabel(self.resonator)
        self.dim_lg.setGeometry(QtCore.QRect(230, 25, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_lg.setFont(font)
        self.dim_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_lg.setObjectName(_fromUtf8("dim_lg"))
        self.name_lg = QtGui.QLabel(self.resonator)
        self.name_lg.setGeometry(QtCore.QRect(110, 25, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_lg.setFont(font)
        self.name_lg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_lg.setObjectName(_fromUtf8("name_lg"))
        self.name_thickness_medium = QtGui.QLabel(self.resonator)
        self.name_thickness_medium.setGeometry(QtCore.QRect(0, 0, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_thickness_medium.setFont(font)
        self.name_thickness_medium.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_thickness_medium.setObjectName(_fromUtf8("name_thickness_medium"))
        self.dim_la = QtGui.QLabel(self.resonator)
        self.dim_la.setGeometry(QtCore.QRect(230, 80, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_la.setFont(font)
        self.dim_la.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_la.setObjectName(_fromUtf8("dim_la"))
        self.name_thickness_absorber = QtGui.QLabel(self.resonator)
        self.name_thickness_absorber.setGeometry(QtCore.QRect(0, 55, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_thickness_absorber.setFont(font)
        self.name_thickness_absorber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_thickness_absorber.setObjectName(_fromUtf8("name_thickness_absorber"))
        self.name_la = QtGui.QLabel(self.resonator)
        self.name_la.setGeometry(QtCore.QRect(110, 80, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_la.setFont(font)
        self.name_la.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_la.setObjectName(_fromUtf8("name_la"))
        self.name_laser_beam_radius = QtGui.QLabel(self.resonator)
        self.name_laser_beam_radius.setGeometry(QtCore.QRect(0, 110, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_laser_beam_radius.setFont(font)
        self.name_laser_beam_radius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_laser_beam_radius.setObjectName(_fromUtf8("name_laser_beam_radius"))
        self.dim_rl = QtGui.QLabel(self.resonator)
        self.dim_rl.setGeometry(QtCore.QRect(230, 135, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_rl.setFont(font)
        self.dim_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_rl.setObjectName(_fromUtf8("dim_rl"))
        self.name_rl = QtGui.QLabel(self.resonator)
        self.name_rl.setGeometry(QtCore.QRect(110, 135, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_rl.setFont(font)
        self.name_rl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_rl.setObjectName(_fromUtf8("name_rl"))
        self.value_n = QtGui.QDoubleSpinBox(self.resonator)
        self.value_n.setGeometry(QtCore.QRect(170, 210, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_n.setFont(font)
        self.value_n.setAlignment(QtCore.Qt.AlignCenter)
        self.value_n.setAccelerated(True)
        self.value_n.setPrefix(_fromUtf8(""))
        self.value_n.setDecimals(4)
        self.value_n.setMinimum(1.0)
        self.value_n.setMaximum(5.0)
        self.value_n.setSingleStep(0.0001)
        self.value_n.setProperty("value", 1.8169)
        self.value_n.setObjectName(_fromUtf8("value_n"))
        self.name_YAG_index = QtGui.QLabel(self.resonator)
        self.name_YAG_index.setGeometry(QtCore.QRect(0, 165, 255, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_YAG_index.setFont(font)
        self.name_YAG_index.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_YAG_index.setWordWrap(True)
        self.name_YAG_index.setObjectName(_fromUtf8("name_YAG_index"))
        self.name_n = QtGui.QLabel(self.resonator)
        self.name_n.setGeometry(QtCore.QRect(110, 210, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_n.setFont(font)
        self.name_n.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_n.setObjectName(_fromUtf8("name_n"))
        self.input_parameter.addItem(self.resonator, _fromUtf8(""))
        self.crosssections = QtGui.QWidget()
        self.crosssections.setGeometry(QtCore.QRect(0, 0, 263, 379))
        self.crosssections.setObjectName(_fromUtf8("crosssections"))
        self.value_sigma_g = scspin.ScientificDoubleSpinBox(self.crosssections)
        self.value_sigma_g.setGeometry(QtCore.QRect(140, 50, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_sigma_g.setFont(font)
        self.value_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_g.setAccelerated(True)
        self.value_sigma_g.setPrefix(_fromUtf8(""))
        self.value_sigma_g.setSuffix(_fromUtf8(""))
        self.value_sigma_g.setDecimals(21)
        self.value_sigma_g.setMaximum(1e-18)
        self.value_sigma_g.setSingleStep(1e-20)
        self.value_sigma_g.setProperty("value", 3.5e-19)
        self.value_sigma_g.setObjectName(_fromUtf8("value_sigma_g"))
        self.value_sigma_a1 = scspin.ScientificDoubleSpinBox(self.crosssections)
        self.value_sigma_a1.setGeometry(QtCore.QRect(140, 130, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_sigma_a1.setFont(font)
        self.value_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_a1.setAccelerated(True)
        self.value_sigma_a1.setPrefix(_fromUtf8(""))
        self.value_sigma_a1.setSuffix(_fromUtf8(""))
        self.value_sigma_a1.setDecimals(21)
        self.value_sigma_a1.setMaximum(1e-17)
        self.value_sigma_a1.setSingleStep(1e-19)
        self.value_sigma_a1.setProperty("value", 2.4e-18)
        self.value_sigma_a1.setObjectName(_fromUtf8("value_sigma_a1"))
        self.value_sigma_a2 = scspin.ScientificDoubleSpinBox(self.crosssections)
        self.value_sigma_a2.setGeometry(QtCore.QRect(140, 210, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_sigma_a2.setFont(font)
        self.value_sigma_a2.setAutoFillBackground(True)
        self.value_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_a2.setAccelerated(True)
        self.value_sigma_a2.setPrefix(_fromUtf8(""))
        self.value_sigma_a2.setSuffix(_fromUtf8(""))
        self.value_sigma_a2.setDecimals(21)
        self.value_sigma_a2.setMaximum(1e-18)
        self.value_sigma_a2.setSingleStep(1e-20)
        self.value_sigma_a2.setProperty("value", 2.8e-19)
        self.value_sigma_a2.setObjectName(_fromUtf8("value_sigma_a2"))
        self.name_cross_laser = QtGui.QLabel(self.crosssections)
        self.name_cross_laser.setGeometry(QtCore.QRect(0, 5, 255, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_cross_laser.setFont(font)
        self.name_cross_laser.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_cross_laser.setWordWrap(True)
        self.name_cross_laser.setObjectName(_fromUtf8("name_cross_laser"))
        self.dim_sigma_g = QtGui.QLabel(self.crosssections)
        self.dim_sigma_g.setGeometry(QtCore.QRect(220, 50, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_sigma_g.setFont(font)
        self.dim_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_g.setObjectName(_fromUtf8("dim_sigma_g"))
        self.name_sigma_g = QtGui.QLabel(self.crosssections)
        self.name_sigma_g.setGeometry(QtCore.QRect(55, 50, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_sigma_g.setFont(font)
        self.name_sigma_g.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_sigma_g.setObjectName(_fromUtf8("name_sigma_g"))
        self.dim_sigma_a1 = QtGui.QLabel(self.crosssections)
        self.dim_sigma_a1.setGeometry(QtCore.QRect(220, 130, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_sigma_a1.setFont(font)
        self.dim_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_a1.setObjectName(_fromUtf8("dim_sigma_a1"))
        self.name_cross_Cr_1 = QtGui.QLabel(self.crosssections)
        self.name_cross_Cr_1.setGeometry(QtCore.QRect(0, 85, 255, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_cross_Cr_1.setFont(font)
        self.name_cross_Cr_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_cross_Cr_1.setWordWrap(True)
        self.name_cross_Cr_1.setObjectName(_fromUtf8("name_cross_Cr_1"))
        self.name_sigma_a1 = QtGui.QLabel(self.crosssections)
        self.name_sigma_a1.setGeometry(QtCore.QRect(55, 130, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_sigma_a1.setFont(font)
        self.name_sigma_a1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_sigma_a1.setObjectName(_fromUtf8("name_sigma_a1"))
        self.dim_sigma_a2 = QtGui.QLabel(self.crosssections)
        self.dim_sigma_a2.setGeometry(QtCore.QRect(220, 210, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_sigma_a2.setFont(font)
        self.dim_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_a2.setObjectName(_fromUtf8("dim_sigma_a2"))
        self.name_sigma_a2 = QtGui.QLabel(self.crosssections)
        self.name_sigma_a2.setGeometry(QtCore.QRect(55, 210, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_sigma_a2.setFont(font)
        self.name_sigma_a2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_sigma_a2.setObjectName(_fromUtf8("name_sigma_a2"))
        self.name_cross_Cr_2 = QtGui.QLabel(self.crosssections)
        self.name_cross_Cr_2.setGeometry(QtCore.QRect(0, 165, 255, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_cross_Cr_2.setFont(font)
        self.name_cross_Cr_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_cross_Cr_2.setWordWrap(True)
        self.name_cross_Cr_2.setObjectName(_fromUtf8("name_cross_Cr_2"))
        self.input_parameter.addItem(self.crosssections, _fromUtf8(""))
        self.concentrations = QtGui.QWidget()
        self.concentrations.setGeometry(QtCore.QRect(0, 0, 263, 379))
        self.concentrations.setObjectName(_fromUtf8("concentrations"))
        self.value_Ng_total = scspin.ScientificDoubleSpinBox(self.concentrations)
        self.value_Ng_total.setGeometry(QtCore.QRect(130, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_Ng_total.setFont(font)
        self.value_Ng_total.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Ng_total.setAccelerated(True)
        self.value_Ng_total.setPrefix(_fromUtf8(""))
        self.value_Ng_total.setSuffix(_fromUtf8(""))
        self.value_Ng_total.setDecimals(0)
        self.value_Ng_total.setMinimum(0.0)
        self.value_Ng_total.setMaximum(1e21)
        self.value_Ng_total.setSingleStep(1e15)
        self.value_Ng_total.setProperty("value", 1.66e17)
        self.value_Ng_total.setObjectName(_fromUtf8("value_Ng_total"))
        self.value_Ng_total_perc = QtGui.QDoubleSpinBox(self.concentrations)
        self.value_Ng_total_perc.setGeometry(QtCore.QRect(130, 90, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_Ng_total_perc.setFont(font)
        self.value_Ng_total_perc.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Ng_total_perc.setAccelerated(True)
        self.value_Ng_total_perc.setPrefix(_fromUtf8(""))
        self.value_Ng_total_perc.setSuffix(_fromUtf8(""))
        self.value_Ng_total_perc.setMaximum(10.0)
        self.value_Ng_total_perc.setSingleStep(0.01)
        self.value_Ng_total_perc.setProperty("value", 1.2)
        self.value_Ng_total_perc.setObjectName(_fromUtf8("value_Ng_total_perc"))
        self.value_Na_total = scspin.ScientificDoubleSpinBox(self.concentrations)
        self.value_Na_total.setGeometry(QtCore.QRect(130, 150, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_Na_total.setFont(font)
        self.value_Na_total.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Na_total.setAccelerated(True)
        self.value_Na_total.setPrefix(_fromUtf8(""))
        self.value_Na_total.setSuffix(_fromUtf8(""))
        self.value_Na_total.setDecimals(0)
        self.value_Na_total.setMaximum(1e20)
        self.value_Na_total.setSingleStep(1e15)
        self.value_Na_total.setProperty("value", 1e17)
        self.value_Na_total.setObjectName(_fromUtf8("value_Na_total"))
        self.name_conc_activ = QtGui.QLabel(self.concentrations)
        self.name_conc_activ.setGeometry(QtCore.QRect(0, 5, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_conc_activ.setFont(font)
        self.name_conc_activ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_conc_activ.setWordWrap(True)
        self.name_conc_activ.setObjectName(_fromUtf8("name_conc_activ"))
        self.name_Ng_total = QtGui.QLabel(self.concentrations)
        self.name_Ng_total.setGeometry(QtCore.QRect(45, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_Ng_total.setFont(font)
        self.name_Ng_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_Ng_total.setObjectName(_fromUtf8("name_Ng_total"))
        self.dim_Ng_total = QtGui.QLabel(self.concentrations)
        self.dim_Ng_total.setGeometry(QtCore.QRect(210, 30, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_Ng_total.setFont(font)
        self.dim_Ng_total.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Ng_total.setObjectName(_fromUtf8("dim_Ng_total"))
        self.dim_Ng_total_perc = QtGui.QLabel(self.concentrations)
        self.dim_Ng_total_perc.setGeometry(QtCore.QRect(210, 90, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_Ng_total_perc.setFont(font)
        self.dim_Ng_total_perc.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Ng_total_perc.setObjectName(_fromUtf8("dim_Ng_total_perc"))
        self.name_conc_activ_perc = QtGui.QLabel(self.concentrations)
        self.name_conc_activ_perc.setGeometry(QtCore.QRect(0, 65, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_conc_activ_perc.setFont(font)
        self.name_conc_activ_perc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_conc_activ_perc.setWordWrap(True)
        self.name_conc_activ_perc.setObjectName(_fromUtf8("name_conc_activ_perc"))
        self.name_Ng_total_perc = QtGui.QLabel(self.concentrations)
        self.name_Ng_total_perc.setGeometry(QtCore.QRect(5, 90, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_Ng_total_perc.setFont(font)
        self.name_Ng_total_perc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_Ng_total_perc.setObjectName(_fromUtf8("name_Ng_total_perc"))
        self.dim_Na_total = QtGui.QLabel(self.concentrations)
        self.dim_Na_total.setGeometry(QtCore.QRect(210, 150, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_Na_total.setFont(font)
        self.dim_Na_total.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Na_total.setObjectName(_fromUtf8("dim_Na_total"))
        self.name_Na_total = QtGui.QLabel(self.concentrations)
        self.name_Na_total.setGeometry(QtCore.QRect(45, 150, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_Na_total.setFont(font)
        self.name_Na_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_Na_total.setObjectName(_fromUtf8("name_Na_total"))
        self.name_conc_Cr = QtGui.QLabel(self.concentrations)
        self.name_conc_Cr.setGeometry(QtCore.QRect(0, 125, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_conc_Cr.setFont(font)
        self.name_conc_Cr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_conc_Cr.setWordWrap(True)
        self.name_conc_Cr.setObjectName(_fromUtf8("name_conc_Cr"))
        self.input_parameter.addItem(self.concentrations, _fromUtf8(""))
        self.losses = QtGui.QWidget()
        self.losses.setGeometry(QtCore.QRect(0, 0, 263, 379))
        self.losses.setObjectName(_fromUtf8("losses"))
        self.value_alpha_p = scspin.ScientificDoubleSpinBox(self.losses)
        self.value_alpha_p.setGeometry(QtCore.QRect(130, 45, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_alpha_p.setFont(font)
        self.value_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.value_alpha_p.setPrefix(_fromUtf8(""))
        self.value_alpha_p.setSuffix(_fromUtf8(""))
        self.value_alpha_p.setDecimals(8)
        self.value_alpha_p.setMaximum(1e-01)
        self.value_alpha_p.setSingleStep(1e-04)
        self.value_alpha_p.setProperty("value", 5e-03)
        self.value_alpha_p.setObjectName(_fromUtf8("value_alpha_p"))
        self.value_R1 = QtGui.QDoubleSpinBox(self.losses)
        self.value_R1.setGeometry(QtCore.QRect(200, 105, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_R1.setFont(font)
        self.value_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_R1.setAccelerated(True)
        self.value_R1.setPrefix(_fromUtf8(""))
        self.value_R1.setMaximum(1.0)
        self.value_R1.setSingleStep(0.01)
        self.value_R1.setProperty("value", 1.0)
        self.value_R1.setObjectName(_fromUtf8("value_R1"))
        self.value_R2 = QtGui.QDoubleSpinBox(self.losses)
        self.value_R2.setGeometry(QtCore.QRect(200, 160, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_R2.setFont(font)
        self.value_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_R2.setAccelerated(True)
        self.value_R2.setPrefix(_fromUtf8(""))
        self.value_R2.setMaximum(1.0)
        self.value_R2.setSingleStep(0.01)
        self.value_R2.setProperty("value", 0.99)
        self.value_R2.setObjectName(_fromUtf8("value_R2"))
        self.dim_alpha_p = QtGui.QLabel(self.losses)
        self.dim_alpha_p.setGeometry(QtCore.QRect(210, 45, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_alpha_p.setFont(font)
        self.dim_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_alpha_p.setObjectName(_fromUtf8("dim_alpha_p"))
        self.name_alpha_p = QtGui.QLabel(self.losses)
        self.name_alpha_p.setGeometry(QtCore.QRect(45, 45, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_alpha_p.setFont(font)
        self.name_alpha_p.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_alpha_p.setObjectName(_fromUtf8("name_alpha_p"))
        self.name_absorb_coef = QtGui.QLabel(self.losses)
        self.name_absorb_coef.setGeometry(QtCore.QRect(0, 0, 255, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_absorb_coef.setFont(font)
        self.name_absorb_coef.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_absorb_coef.setWordWrap(True)
        self.name_absorb_coef.setObjectName(_fromUtf8("name_absorb_coef"))
        self.name_input_mirror = QtGui.QLabel(self.losses)
        self.name_input_mirror.setGeometry(QtCore.QRect(0, 80, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_input_mirror.setFont(font)
        self.name_input_mirror.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_input_mirror.setWordWrap(True)
        self.name_input_mirror.setObjectName(_fromUtf8("name_input_mirror"))
        self.name_R1 = QtGui.QLabel(self.losses)
        self.name_R1.setGeometry(QtCore.QRect(150, 105, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_R1.setFont(font)
        self.name_R1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_R1.setObjectName(_fromUtf8("name_R1"))
        self.name_output_mirror = QtGui.QLabel(self.losses)
        self.name_output_mirror.setGeometry(QtCore.QRect(0, 135, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_output_mirror.setFont(font)
        self.name_output_mirror.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_output_mirror.setWordWrap(True)
        self.name_output_mirror.setObjectName(_fromUtf8("name_output_mirror"))
        self.name_R2 = QtGui.QLabel(self.losses)
        self.name_R2.setGeometry(QtCore.QRect(150, 160, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_R2.setFont(font)
        self.name_R2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_R2.setObjectName(_fromUtf8("name_R2"))
        self.input_parameter.addItem(self.losses, _fromUtf8(""))
        self.pumping = QtGui.QWidget()
        self.pumping.setGeometry(QtCore.QRect(0, 0, 263, 379))
        self.pumping.setObjectName(_fromUtf8("pumping"))
        self.value_Pi = QtGui.QDoubleSpinBox(self.pumping)
        self.value_Pi.setGeometry(QtCore.QRect(160, 30, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_Pi.setFont(font)
        self.value_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Pi.setAccelerated(True)
        self.value_Pi.setPrefix(_fromUtf8(""))
        self.value_Pi.setSuffix(_fromUtf8(""))
        self.value_Pi.setMaximum(100.0)
        self.value_Pi.setSingleStep(0.01)
        self.value_Pi.setProperty("value", 0.2)
        self.value_Pi.setObjectName(_fromUtf8("value_Pi"))
        self.value_wavelength = QtGui.QDoubleSpinBox(self.pumping)
        self.value_wavelength.setGeometry(QtCore.QRect(160, 90, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_wavelength.setFont(font)
        self.value_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.value_wavelength.setAccelerated(True)
        self.value_wavelength.setPrefix(_fromUtf8(""))
        self.value_wavelength.setSuffix(_fromUtf8(""))
        self.value_wavelength.setDecimals(3)
        self.value_wavelength.setMaximum(5.0)
        self.value_wavelength.setSingleStep(0.001)
        self.value_wavelength.setProperty("value", 0.808)
        self.value_wavelength.setObjectName(_fromUtf8("value_wavelength"))
        self.value_rp = QtGui.QSpinBox(self.pumping)
        self.value_rp.setGeometry(QtCore.QRect(160, 140, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.value_rp.setFont(font)
        self.value_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.value_rp.setAccelerated(True)
        self.value_rp.setSuffix(_fromUtf8(""))
        self.value_rp.setPrefix(_fromUtf8(""))
        self.value_rp.setMaximum(1000)
        self.value_rp.setProperty("value", 300)
        self.value_rp.setObjectName(_fromUtf8("value_rp"))
        self.dim_Pi = QtGui.QLabel(self.pumping)
        self.dim_Pi.setGeometry(QtCore.QRect(230, 30, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_Pi.setFont(font)
        self.dim_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Pi.setObjectName(_fromUtf8("dim_Pi"))
        self.name_pump_power = QtGui.QLabel(self.pumping)
        self.name_pump_power.setGeometry(QtCore.QRect(0, 5, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_pump_power.setFont(font)
        self.name_pump_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_pump_power.setWordWrap(True)
        self.name_pump_power.setObjectName(_fromUtf8("name_pump_power"))
        self.name_Pi = QtGui.QLabel(self.pumping)
        self.name_Pi.setGeometry(QtCore.QRect(115, 30, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_Pi.setFont(font)
        self.name_Pi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_Pi.setObjectName(_fromUtf8("name_Pi"))
        self.dim_wavelength = QtGui.QLabel(self.pumping)
        self.dim_wavelength.setGeometry(QtCore.QRect(230, 90, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_wavelength.setFont(font)
        self.dim_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_wavelength.setObjectName(_fromUtf8("dim_wavelength"))
        self.name_wavelength = QtGui.QLabel(self.pumping)
        self.name_wavelength.setGeometry(QtCore.QRect(55, 90, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_wavelength.setFont(font)
        self.name_wavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_wavelength.setObjectName(_fromUtf8("name_wavelength"))
        self.name_pump_wavelength = QtGui.QLabel(self.pumping)
        self.name_pump_wavelength.setGeometry(QtCore.QRect(0, 65, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_pump_wavelength.setFont(font)
        self.name_pump_wavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_pump_wavelength.setWordWrap(True)
        self.name_pump_wavelength.setObjectName(_fromUtf8("name_pump_wavelength"))
        self.dim_rp = QtGui.QLabel(self.pumping)
        self.dim_rp.setGeometry(QtCore.QRect(220, 140, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.dim_rp.setFont(font)
        self.dim_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_rp.setObjectName(_fromUtf8("dim_rp"))
        self.name_pump_beam_radius = QtGui.QLabel(self.pumping)
        self.name_pump_beam_radius.setGeometry(QtCore.QRect(0, 115, 255, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.name_pump_beam_radius.setFont(font)
        self.name_pump_beam_radius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_pump_beam_radius.setWordWrap(True)
        self.name_pump_beam_radius.setObjectName(_fromUtf8("name_pump_beam_radius"))
        self.name_rp = QtGui.QLabel(self.pumping)
        self.name_rp.setGeometry(QtCore.QRect(115, 140, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.name_rp.setFont(font)
        self.name_rp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_rp.setObjectName(_fromUtf8("name_rp"))
        self.input_parameter.addItem(self.pumping, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.input_parameter, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 2, 2)
        spacerItem6 = QtGui.QSpacerItem(40, 2, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 2, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setMinimumSize(QtCore.QSize(20, 10))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainwindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainwindow.setStatusBar(self.statusbar)
        self.actionOpen_config = QtGui.QAction(mainwindow)
        self.actionOpen_config.setObjectName(_fromUtf8("actionOpen_config"))
        self.actionSave_config = QtGui.QAction(mainwindow)
        self.actionSave_config.setObjectName(_fromUtf8("actionSave_config"))
        self.actionQuit = QtGui.QAction(mainwindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionExpand = QtGui.QAction(mainwindow)
        self.actionExpand.setObjectName(_fromUtf8("actionExpand"))
        self.actionCalculate = QtGui.QAction(mainwindow)
        self.actionCalculate.setObjectName(_fromUtf8("actionCalculate"))
        self.actionHelp = QtGui.QAction(mainwindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(mainwindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuView.addAction(self.actionExpand)
        self.menuRun.addAction(self.actionCalculate)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionOpen_config)
        self.menuFile.addAction(self.actionSave_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainwindow)
        self.input_parameter.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), mainwindow.close)
        QtCore.QObject.connect(self.button_quit, QtCore.SIGNAL(_fromUtf8("clicked()")), mainwindow.close)
        QtCore.QObject.connect(self.actionExpand, QtCore.SIGNAL(_fromUtf8("activated()")), mainwindow.showMaximized)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        mainwindow.setWindowTitle(_translate("mainwindow", "YAG:Nd Laser Simulation", None))
        self.button_quit.setText(_translate("mainwindow", "Quit", None))
        self.button_calculate.setText(_translate("mainwindow", "Calculate", None))
        self.name_input_param.setText(_translate("mainwindow", "Input Parameters", None))
        self.name_calc_time.setText(_translate("mainwindow", "Calculation Time", None))
        self.name_tau_m.setText(_translate("mainwindow", "tau<sub>m</sub> = ", None))
        self.dim_tau_m.setText(_translate("mainwindow", "μs", None))
        self.name_calc_step.setText(_translate("mainwindow", "Time step in calculations", None))
        self.name_dt_2.setText(_translate("mainwindow", "dt = ", None))
        self.dim_dt_2.setText(_translate("mainwindow", "μs", None))
        self.dim_tau_g.setText(_translate("mainwindow", "μs", None))
        self.name_tau_g.setText(_translate("mainwindow", "tau<sub>g</sub> = ", None))
        self.name_high_level.setText(_translate("mainwindow", "Lifetime of high laser level", None))
        self.dim_tau_a.setText(_translate("mainwindow", "μs", None))
        self.name_cr_level.setText(_translate("mainwindow", "Lifetime of Cr<sup>4+</sup> excited level", None))
        self.name_tau_a.setText(_translate("mainwindow", "tau<sub>a</sub> = ", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.times), _translate("mainwindow", "Times", None))
        self.dim_lg.setText(_translate("mainwindow", "μm", None))
        self.name_lg.setText(_translate("mainwindow", "l<sub>g</sub> = ", None))
        self.name_thickness_medium.setText(_translate("mainwindow", "Thickness of active medium", None))
        self.dim_la.setText(_translate("mainwindow", "μm", None))
        self.name_thickness_absorber.setText(_translate("mainwindow", "Absorber thickness", None))
        self.name_la.setText(_translate("mainwindow", "l<sub>a</sub> = ", None))
        self.name_laser_beam_radius.setText(_translate("mainwindow", "Laser beam radius", None))
        self.dim_rl.setText(_translate("mainwindow", "μm", None))
        self.name_rl.setText(_translate("mainwindow", "r<sub>l</sub> = ", None))
        self.name_YAG_index.setText(_translate("mainwindow", "YAG:Nd refractive index at 1.064 um", None))
        self.name_n.setText(_translate("mainwindow", "n = ", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.resonator), _translate("mainwindow", "Resonator", None))
        self.name_cross_laser.setText(_translate("mainwindow", " Efficient cross-section of laser transition", None))
        self.dim_sigma_g.setText(_translate("mainwindow", "μm<sup>2</sup>", None))
        self.name_sigma_g.setText(_translate("mainwindow", "σ<sub>g</sub> =", None))
        self.dim_sigma_a1.setText(_translate("mainwindow", "μm<sup>2</sup>", None))
        self.name_cross_Cr_1.setText(_translate("mainwindow", "Cross-section  between Cr<sup>4+</sup> levels", None))
        self.name_sigma_a1.setText(_translate("mainwindow", "σ<sub>a1</sub> =", None))
        self.dim_sigma_a2.setText(_translate("mainwindow", "μm<sup>2</sup>", None))
        self.name_sigma_a2.setText(_translate("mainwindow", "σ<sub>a2</sub> =", None))
        self.name_cross_Cr_2.setText(_translate("mainwindow", "Cross-section  between Cr<sup>4+</sup> levels", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.crosssections), _translate("mainwindow", "Cross-sections", None))
        self.name_conc_activ.setText(_translate("mainwindow", "Activator concentration", None))
        self.name_Ng_total.setText(_translate("mainwindow", "N<sub>g total</sub> = ", None))
        self.dim_Ng_total.setText(_translate("mainwindow", "μm<sup>-3</sup>", None))
        self.dim_Ng_total_perc.setText(_translate("mainwindow", "%", None))
        self.name_conc_activ_perc.setText(_translate("mainwindow", "Activator concentration at %", None))
        self.name_Ng_total_perc.setText(_translate("mainwindow", "Ng_total_perc = ", None))
        self.dim_Na_total.setText(_translate("mainwindow", "μm<sup>-3</sup>", None))
        self.name_Na_total.setText(_translate("mainwindow", "N<sub>a total</sub> = ", None))
        self.name_conc_Cr.setText(_translate("mainwindow", "Cr<sup>4+</sup> ion concentration", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.concentrations), _translate("mainwindow", "Concentrations", None))
        self.dim_alpha_p.setText(_translate("mainwindow", "μm<sup>-1</sup>", None))
        self.name_alpha_p.setText(_translate("mainwindow", "α<sub>p</sub> = ", None))
        self.name_absorb_coef.setText(_translate("mainwindow", "Absorption coefficient on the wavelength", None))
        self.name_input_mirror.setText(_translate("mainwindow", "Reflectivity of input mirror", None))
        self.name_R1.setText(_translate("mainwindow", "R<sub>1</sub> = ", None))
        self.name_output_mirror.setText(_translate("mainwindow", "Reflectivity of output mirror", None))
        self.name_R2.setText(_translate("mainwindow", "R<sub>2</sub> = ", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.losses), _translate("mainwindow", "Losses", None))
        self.dim_Pi.setText(_translate("mainwindow", "W", None))
        self.name_pump_power.setText(_translate("mainwindow", "Pumping power", None))
        self.name_Pi.setText(_translate("mainwindow", "P<sub>i</sub> =", None))
        self.dim_wavelength.setText(_translate("mainwindow", "μm", None))
        self.name_wavelength.setText(_translate("mainwindow", "wavelength =", None))
        self.name_pump_wavelength.setText(_translate("mainwindow", "Pumping wavelength", None))
        self.dim_rp.setText(_translate("mainwindow", "μm", None))
        self.name_pump_beam_radius.setText(_translate("mainwindow", "Pumping beam radius", None))
        self.name_rp.setText(_translate("mainwindow", "r<sub>p</sub> =", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.pumping), _translate("mainwindow", "Pumping", None))
        self.menuView.setTitle(_translate("mainwindow", "View", None))
        self.menuRun.setTitle(_translate("mainwindow", "Run", None))
        self.menuHelp.setTitle(_translate("mainwindow", "Help", None))
        self.menuFile.setTitle(_translate("mainwindow", "File", None))
        self.actionOpen_config.setText(_translate("mainwindow", "Open config", None))
        self.actionOpen_config.setShortcut(_translate("mainwindow", "Ctrl+O", None))
        self.actionSave_config.setText(_translate("mainwindow", "Save config", None))
        self.actionSave_config.setShortcut(_translate("mainwindow", "Ctrl+S", None))
        self.actionQuit.setText(_translate("mainwindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("mainwindow", "Ctrl+Q", None))
        self.actionExpand.setText(_translate("mainwindow", "Expand", None))
        self.actionExpand.setShortcut(_translate("mainwindow", "Ctrl+F", None))
        self.actionCalculate.setText(_translate("mainwindow", "Calculate", None))
        self.actionHelp.setText(_translate("mainwindow", "Help", None))
        self.actionAbout.setText(_translate("mainwindow", "About", None))

