# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laserYAGNd.ui'
#
# Created: Sun Oct 26 17:19:49 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import scientificspin as scspin

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Sans"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget.setFont(font)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(2, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(2, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(2, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 2, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.plot_ndna = QtGui.QFrame(self.centralwidget)
        self.plot_ndna.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_ndna.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_ndna.setObjectName(_fromUtf8("plot_ndna"))
        self.gridLayout.addWidget(self.plot_ndna, 1, 2, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(275, 2, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 0, 1, 2)
        self.button_quit = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_quit.setFont(font)
        self.button_quit.setObjectName(_fromUtf8("button_quit"))
        self.gridLayout.addWidget(self.button_quit, 3, 4, 1, 1)
        self.plot_P = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_P.sizePolicy().hasHeightForWidth())
        self.plot_P.setSizePolicy(sizePolicy)
        self.plot_P.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot_P.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_P.setObjectName(_fromUtf8("plot_P"))
        self.gridLayout.addWidget(self.plot_P, 2, 2, 1, 3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.input_title = QtGui.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 9, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.input_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_title.setFont(font)
        self.input_title.setAutoFillBackground(True)
        self.input_title.setFrame(False)
        self.input_title.setAlignment(QtCore.Qt.AlignCenter)
        self.input_title.setReadOnly(True)
        self.input_title.setObjectName(_fromUtf8("input_title"))
        self.gridLayout_2.addWidget(self.input_title, 0, 0, 1, 1)
        self.button_calculate = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_calculate.setFont(font)
        self.button_calculate.setCheckable(False)
        self.button_calculate.setObjectName(_fromUtf8("button_calculate"))
        self.gridLayout_2.addWidget(self.button_calculate, 2, 0, 1, 1)
        self.input_parameter = QtGui.QToolBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_parameter.sizePolicy().hasHeightForWidth())
        self.input_parameter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_parameter.setFont(font)
        self.input_parameter.setAutoFillBackground(False)
        self.input_parameter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.input_parameter.setFrameShadow(QtGui.QFrame.Sunken)
        self.input_parameter.setLineWidth(1)
        self.input_parameter.setMidLineWidth(1)
        self.input_parameter.setObjectName(_fromUtf8("input_parameter"))
        self.times = QtGui.QWidget()
        self.times.setGeometry(QtCore.QRect(0, 0, 263, 423))
        self.times.setObjectName(_fromUtf8("times"))
        self.name1_times = QtGui.QLineEdit(self.times)
        self.name1_times.setGeometry(QtCore.QRect(0, 110, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name1_times.setFont(font)
        self.name1_times.setAlignment(QtCore.Qt.AlignCenter)
        self.name1_times.setReadOnly(True)
        self.name1_times.setObjectName(_fromUtf8("name1_times"))
        self.value_tau_g = QtGui.QSpinBox(self.times)
        self.value_tau_g.setGeometry(QtCore.QRect(150, 130, 61, 22))
        self.value_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_g.setAccelerated(True)
        self.value_tau_g.setSuffix(_fromUtf8(""))
        self.value_tau_g.setPrefix(_fromUtf8(""))
        self.value_tau_g.setMaximum(1000)
        self.value_tau_g.setProperty("value", 230)
        self.value_tau_g.setObjectName(_fromUtf8("value_tau_g"))
        self.name2_times = QtGui.QLineEdit(self.times)
        self.name2_times.setGeometry(QtCore.QRect(0, 160, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name2_times.setFont(font)
        self.name2_times.setAlignment(QtCore.Qt.AlignCenter)
        self.name2_times.setReadOnly(True)
        self.name2_times.setObjectName(_fromUtf8("name2_times"))
        self.value_tau_a = QtGui.QDoubleSpinBox(self.times)
        self.value_tau_a.setGeometry(QtCore.QRect(150, 180, 61, 22))
        self.value_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_a.setAccelerated(True)
        self.value_tau_a.setPrefix(_fromUtf8(""))
        self.value_tau_a.setSuffix(_fromUtf8(""))
        self.value_tau_a.setMaximum(10.0)
        self.value_tau_a.setSingleStep(0.01)
        self.value_tau_a.setProperty("value", 3.5)
        self.value_tau_a.setObjectName(_fromUtf8("value_tau_a"))
        self.name1_calc_time = QtGui.QLineEdit(self.times)
        self.name1_calc_time.setGeometry(QtCore.QRect(0, 10, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name1_calc_time.setFont(font)
        self.name1_calc_time.setAlignment(QtCore.Qt.AlignCenter)
        self.name1_calc_time.setReadOnly(True)
        self.name1_calc_time.setObjectName(_fromUtf8("name1_calc_time"))
        self.value_tau_m = QtGui.QSpinBox(self.times)
        self.value_tau_m.setGeometry(QtCore.QRect(150, 30, 61, 22))
        self.value_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.value_tau_m.setAccelerated(True)
        self.value_tau_m.setSuffix(_fromUtf8(""))
        self.value_tau_m.setPrefix(_fromUtf8(""))
        self.value_tau_m.setMaximum(100000)
        self.value_tau_m.setProperty("value", 50)
        self.value_tau_m.setObjectName(_fromUtf8("value_tau_m"))
        self.value_dt = QtGui.QDoubleSpinBox(self.times)
        self.value_dt.setGeometry(QtCore.QRect(150, 80, 61, 22))
        self.value_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.value_dt.setAccelerated(True)
        self.value_dt.setPrefix(_fromUtf8(""))
        self.value_dt.setSuffix(_fromUtf8(""))
        self.value_dt.setDecimals(3)
        self.value_dt.setMaximum(1.0)
        self.value_dt.setSingleStep(0.001)
        self.value_dt.setProperty("value", 0.01)
        self.value_dt.setObjectName(_fromUtf8("value_dt"))
        self.name1_time_step = QtGui.QLineEdit(self.times)
        self.name1_time_step.setGeometry(QtCore.QRect(0, 60, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name1_time_step.setFont(font)
        self.name1_time_step.setAlignment(QtCore.Qt.AlignCenter)
        self.name1_time_step.setReadOnly(True)
        self.name1_time_step.setObjectName(_fromUtf8("name1_time_step"))
        self.name_tau_m = QtGui.QLineEdit(self.times)
        self.name_tau_m.setGeometry(QtCore.QRect(80, 30, 71, 22))
        self.name_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.name_tau_m.setReadOnly(True)
        self.name_tau_m.setObjectName(_fromUtf8("name_tau_m"))
        self.dim_tau_m = QtGui.QLineEdit(self.times)
        self.dim_tau_m.setGeometry(QtCore.QRect(210, 30, 51, 22))
        self.dim_tau_m.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_m.setObjectName(_fromUtf8("dim_tau_m"))
        self.dim_dt = QtGui.QLineEdit(self.times)
        self.dim_dt.setGeometry(QtCore.QRect(210, 80, 51, 22))
        self.dim_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_dt.setObjectName(_fromUtf8("dim_dt"))
        self.ldim_tau_g = QtGui.QLineEdit(self.times)
        self.ldim_tau_g.setGeometry(QtCore.QRect(210, 130, 51, 22))
        self.ldim_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.ldim_tau_g.setObjectName(_fromUtf8("ldim_tau_g"))
        self.dim_tau_a = QtGui.QLineEdit(self.times)
        self.dim_tau_a.setGeometry(QtCore.QRect(210, 180, 51, 22))
        self.dim_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_tau_a.setObjectName(_fromUtf8("dim_tau_a"))
        self.name_dt = QtGui.QLineEdit(self.times)
        self.name_dt.setGeometry(QtCore.QRect(80, 80, 71, 22))
        self.name_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.name_dt.setReadOnly(True)
        self.name_dt.setObjectName(_fromUtf8("name_dt"))
        self.name_tau_g = QtGui.QLineEdit(self.times)
        self.name_tau_g.setGeometry(QtCore.QRect(80, 130, 71, 21))
        self.name_tau_g.setAlignment(QtCore.Qt.AlignCenter)
        self.name_tau_g.setReadOnly(True)
        self.name_tau_g.setObjectName(_fromUtf8("name_tau_g"))
        self.name_tau_a = QtGui.QLineEdit(self.times)
        self.name_tau_a.setGeometry(QtCore.QRect(80, 180, 71, 22))
        self.name_tau_a.setAlignment(QtCore.Qt.AlignCenter)
        self.name_tau_a.setReadOnly(True)
        self.name_tau_a.setObjectName(_fromUtf8("name_tau_a"))
        self.input_parameter.addItem(self.times, _fromUtf8(""))
        self.dimensions = QtGui.QWidget()
        self.dimensions.setGeometry(QtCore.QRect(0, 0, 263, 423))
        self.dimensions.setObjectName(_fromUtf8("dimensions"))
        self.name_active_medium = QtGui.QLineEdit(self.dimensions)
        self.name_active_medium.setGeometry(QtCore.QRect(0, 0, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_active_medium.setFont(font)
        self.name_active_medium.setAlignment(QtCore.Qt.AlignCenter)
        self.name_active_medium.setReadOnly(True)
        self.name_active_medium.setObjectName(_fromUtf8("name_active_medium"))
        self.value_lg = QtGui.QSpinBox(self.dimensions)
        self.value_lg.setGeometry(QtCore.QRect(150, 20, 61, 22))
        self.value_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.value_lg.setAccelerated(True)
        self.value_lg.setSuffix(_fromUtf8(""))
        self.value_lg.setPrefix(_fromUtf8(""))
        self.value_lg.setMaximum(10000)
        self.value_lg.setProperty("value", 1000)
        self.value_lg.setObjectName(_fromUtf8("value_lg"))
        self.name_absorber = QtGui.QLineEdit(self.dimensions)
        self.name_absorber.setGeometry(QtCore.QRect(0, 50, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_absorber.setFont(font)
        self.name_absorber.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorber.setReadOnly(True)
        self.name_absorber.setObjectName(_fromUtf8("name_absorber"))
        self.value_la = QtGui.QSpinBox(self.dimensions)
        self.value_la.setGeometry(QtCore.QRect(150, 70, 61, 22))
        self.value_la.setAlignment(QtCore.Qt.AlignCenter)
        self.value_la.setAccelerated(True)
        self.value_la.setSuffix(_fromUtf8(""))
        self.value_la.setPrefix(_fromUtf8(""))
        self.value_la.setMaximum(250)
        self.value_la.setProperty("value", 50)
        self.value_la.setObjectName(_fromUtf8("value_la"))
        self.value_rl = QtGui.QSpinBox(self.dimensions)
        self.value_rl.setGeometry(QtCore.QRect(150, 120, 61, 22))
        self.value_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.value_rl.setAccelerated(True)
        self.value_rl.setSuffix(_fromUtf8(""))
        self.value_rl.setPrefix(_fromUtf8(""))
        self.value_rl.setMaximum(1000)
        self.value_rl.setProperty("value", 300)
        self.value_rl.setObjectName(_fromUtf8("value_rl"))
        self.name_beam_radius = QtGui.QLineEdit(self.dimensions)
        self.name_beam_radius.setGeometry(QtCore.QRect(0, 100, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_beam_radius.setFont(font)
        self.name_beam_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.name_beam_radius.setReadOnly(True)
        self.name_beam_radius.setObjectName(_fromUtf8("name_beam_radius"))
        self.value_n = QtGui.QDoubleSpinBox(self.dimensions)
        self.value_n.setGeometry(QtCore.QRect(190, 170, 71, 22))
        self.value_n.setAlignment(QtCore.Qt.AlignCenter)
        self.value_n.setAccelerated(True)
        self.value_n.setPrefix(_fromUtf8(""))
        self.value_n.setDecimals(4)
        self.value_n.setMinimum(1.0)
        self.value_n.setMaximum(5.0)
        self.value_n.setSingleStep(0.0001)
        self.value_n.setProperty("value", 1.8169)
        self.value_n.setObjectName(_fromUtf8("value_n"))
        self.name_index = QtGui.QLineEdit(self.dimensions)
        self.name_index.setGeometry(QtCore.QRect(0, 150, 261, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_index.setFont(font)
        self.name_index.setAlignment(QtCore.Qt.AlignCenter)
        self.name_index.setReadOnly(True)
        self.name_index.setObjectName(_fromUtf8("name_index"))
        self.dim_lg = QtGui.QLineEdit(self.dimensions)
        self.dim_lg.setGeometry(QtCore.QRect(210, 20, 51, 22))
        self.dim_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_lg.setObjectName(_fromUtf8("dim_lg"))
        self.dim_la = QtGui.QLineEdit(self.dimensions)
        self.dim_la.setGeometry(QtCore.QRect(210, 70, 51, 22))
        self.dim_la.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_la.setObjectName(_fromUtf8("dim_la"))
        self.dim_rl = QtGui.QLineEdit(self.dimensions)
        self.dim_rl.setGeometry(QtCore.QRect(210, 120, 51, 22))
        self.dim_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_rl.setObjectName(_fromUtf8("dim_rl"))
        self.name_lg = QtGui.QLineEdit(self.dimensions)
        self.name_lg.setGeometry(QtCore.QRect(110, 20, 41, 22))
        self.name_lg.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lg.setReadOnly(True)
        self.name_lg.setObjectName(_fromUtf8("name_lg"))
        self.name_la = QtGui.QLineEdit(self.dimensions)
        self.name_la.setGeometry(QtCore.QRect(110, 70, 41, 22))
        self.name_la.setAlignment(QtCore.Qt.AlignCenter)
        self.name_la.setReadOnly(True)
        self.name_la.setObjectName(_fromUtf8("name_la"))
        self.name_rl = QtGui.QLineEdit(self.dimensions)
        self.name_rl.setGeometry(QtCore.QRect(110, 120, 41, 22))
        self.name_rl.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rl.setReadOnly(True)
        self.name_rl.setObjectName(_fromUtf8("name_rl"))
        self.name_n = QtGui.QLineEdit(self.dimensions)
        self.name_n.setGeometry(QtCore.QRect(150, 170, 41, 22))
        self.name_n.setAlignment(QtCore.Qt.AlignCenter)
        self.name_n.setReadOnly(True)
        self.name_n.setObjectName(_fromUtf8("name_n"))
        self.input_parameter.addItem(self.dimensions, _fromUtf8(""))
        self.crosssections = QtGui.QWidget()
        self.crosssections.setGeometry(QtCore.QRect(0, 0, 263, 423))
        self.crosssections.setObjectName(_fromUtf8("crosssections"))
        self.name_laser_trans = QtGui.QLineEdit(self.crosssections)
        self.name_laser_trans.setGeometry(QtCore.QRect(0, 0, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_laser_trans.setFont(font)
        self.name_laser_trans.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name_laser_trans.setAlignment(QtCore.Qt.AlignCenter)
        self.name_laser_trans.setReadOnly(True)
        self.name_laser_trans.setObjectName(_fromUtf8("name_laser_trans"))
        self.value_sigma_g = scspin.ScientificDoubleSpinBox(self.crosssections)
        self.value_sigma_g.setGeometry(QtCore.QRect(130, 20, 81, 22))
        self.value_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_g.setAccelerated(True)
        self.value_sigma_g.setPrefix(_fromUtf8(""))
        self.value_sigma_g.setSuffix(_fromUtf8(""))
        self.value_sigma_g.setDecimals(13)
        self.value_sigma_g.setMaximum(1e-10)
        self.value_sigma_g.setSingleStep(1e-12)
        self.value_sigma_g.setProperty("value", 3.5e-11)
        self.value_sigma_g.setObjectName(_fromUtf8("value_sigma_g"))
        self.dim_sigma_g = QtGui.QLineEdit(self.crosssections)
        self.dim_sigma_g.setGeometry(QtCore.QRect(210, 20, 51, 22))
        self.dim_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_g.setReadOnly(True)
        self.dim_sigma_g.setObjectName(_fromUtf8("dim_sigma_g"))
        self.dim_sigma_a1 = QtGui.QLineEdit(self.crosssections)
        self.dim_sigma_a1.setGeometry(QtCore.QRect(210, 70, 51, 22))
        self.dim_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_a1.setReadOnly(True)
        self.dim_sigma_a1.setObjectName(_fromUtf8("dim_sigma_a1"))
        self.name_absorber_levels_1 = QtGui.QLineEdit(self.crosssections)
        self.name_absorber_levels_1.setGeometry(QtCore.QRect(0, 50, 261, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.name_absorber_levels_1.setFont(font)
        self.name_absorber_levels_1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorber_levels_1.setReadOnly(True)
        self.name_absorber_levels_1.setObjectName(_fromUtf8("name_absorber_levels_1"))
        self.value_sigma_a1 = scspin.ScientificDoubleSpinBox(self.crosssections)
        self.value_sigma_a1.setGeometry(QtCore.QRect(130, 70, 81, 22))
        self.value_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_a1.setAccelerated(True)
        self.value_sigma_a1.setPrefix(_fromUtf8(""))
        self.value_sigma_a1.setSuffix(_fromUtf8(""))
        self.value_sigma_a1.setDecimals(13)
        self.value_sigma_a1.setMaximum(1e-9)
        self.value_sigma_a1.setSingleStep(1e-11)
        self.value_sigma_a1.setProperty("value", 2.4e-10)
        self.value_sigma_a1.setObjectName(_fromUtf8("value_sigma_a1"))
        self.dim_sigma_a2 = QtGui.QLineEdit(self.crosssections)
        self.dim_sigma_a2.setGeometry(QtCore.QRect(210, 120, 51, 22))
        self.dim_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_sigma_a2.setReadOnly(True)
        self.dim_sigma_a2.setObjectName(_fromUtf8("dim_sigma_a2"))
        self.name_absorber_levels_2 = QtGui.QLineEdit(self.crosssections)
        self.name_absorber_levels_2.setGeometry(QtCore.QRect(0, 100, 261, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.name_absorber_levels_2.setFont(font)
        self.name_absorber_levels_2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorber_levels_2.setReadOnly(True)
        self.name_absorber_levels_2.setObjectName(_fromUtf8("name_absorber_levels_2"))
        self.value_sigma_a2 = scspin.ScientificDoubleSpinBox(self.crosssections)
        self.value_sigma_a2.setGeometry(QtCore.QRect(130, 120, 81, 22))
        self.value_sigma_a2.setAutoFillBackground(True)
        self.value_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_sigma_a2.setAccelerated(True)
        self.value_sigma_a2.setPrefix(_fromUtf8(""))
        self.value_sigma_a2.setSuffix(_fromUtf8(""))
        self.value_sigma_a2.setDecimals(13)
        self.value_sigma_a2.setMaximum(1e-10)
        self.value_sigma_a2.setSingleStep(1e-12)
        self.value_sigma_a2.setProperty("value", 2.8e-11)
        self.value_sigma_a2.setObjectName(_fromUtf8("value_sigma_a2"))
        self.name_sigma_g = QtGui.QLineEdit(self.crosssections)
        self.name_sigma_g.setGeometry(QtCore.QRect(40, 20, 91, 22))
        self.name_sigma_g.setAlignment(QtCore.Qt.AlignCenter)
        self.name_sigma_g.setReadOnly(True)
        self.name_sigma_g.setObjectName(_fromUtf8("name_sigma_g"))
        self.name_sigma_a1 = QtGui.QLineEdit(self.crosssections)
        self.name_sigma_a1.setGeometry(QtCore.QRect(40, 70, 91, 22))
        self.name_sigma_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_sigma_a1.setReadOnly(True)
        self.name_sigma_a1.setObjectName(_fromUtf8("name_sigma_a1"))
        self.name_sigma_a2 = QtGui.QLineEdit(self.crosssections)
        self.name_sigma_a2.setGeometry(QtCore.QRect(40, 120, 91, 22))
        self.name_sigma_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_sigma_a2.setReadOnly(True)
        self.name_sigma_a2.setObjectName(_fromUtf8("name_sigma_a2"))
        self.input_parameter.addItem(self.crosssections, _fromUtf8(""))
        self.concentrations = QtGui.QWidget()
        self.concentrations.setGeometry(QtCore.QRect(0, 0, 263, 423))
        self.concentrations.setObjectName(_fromUtf8("concentrations"))
        self.name_activator_conc = QtGui.QLineEdit(self.concentrations)
        self.name_activator_conc.setGeometry(QtCore.QRect(0, 0, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_activator_conc.setFont(font)
        self.name_activator_conc.setAlignment(QtCore.Qt.AlignCenter)
        self.name_activator_conc.setReadOnly(True)
        self.name_activator_conc.setObjectName(_fromUtf8("name_activator_conc"))
        self.value_Ng_total = scspin.ScientificDoubleSpinBox(self.concentrations)
        self.value_Ng_total.setGeometry(QtCore.QRect(130, 20, 81, 22))
        self.value_Ng_total.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Ng_total.setAccelerated(True)
        self.value_Ng_total.setPrefix(_fromUtf8(""))
        self.value_Ng_total.setSuffix(_fromUtf8(""))
        self.value_Ng_total.setDecimals(0)
        self.value_Ng_total.setMinimum(0.0)
        self.value_Ng_total.setMaximum(1e9)
        self.value_Ng_total.setSingleStep(1e3)
        self.value_Ng_total.setProperty("value", 1.66e5)
        self.value_Ng_total.setObjectName(_fromUtf8("value_Ng_total"))
        self.dim_Ng_total = QtGui.QLineEdit(self.concentrations)
        self.dim_Ng_total.setGeometry(QtCore.QRect(210, 20, 51, 22))
        self.dim_Ng_total.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Ng_total.setReadOnly(True)
        self.dim_Ng_total.setObjectName(_fromUtf8("dim_Ng_total"))
        self.value_Ng_total_perc = QtGui.QDoubleSpinBox(self.concentrations)
        self.value_Ng_total_perc.setGeometry(QtCore.QRect(150, 70, 61, 22))
        self.value_Ng_total_perc.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Ng_total_perc.setAccelerated(True)
        self.value_Ng_total_perc.setPrefix(_fromUtf8(""))
        self.value_Ng_total_perc.setSuffix(_fromUtf8(""))
        self.value_Ng_total_perc.setMaximum(10.0)
        self.value_Ng_total_perc.setSingleStep(0.01)
        self.value_Ng_total_perc.setProperty("value", 1.2)
        self.value_Ng_total_perc.setObjectName(_fromUtf8("value_Ng_total_perc"))
        self.name_activator_conc_proc = QtGui.QLineEdit(self.concentrations)
        self.name_activator_conc_proc.setGeometry(QtCore.QRect(0, 50, 261, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.name_activator_conc_proc.setFont(font)
        self.name_activator_conc_proc.setAlignment(QtCore.Qt.AlignCenter)
        self.name_activator_conc_proc.setReadOnly(True)
        self.name_activator_conc_proc.setObjectName(_fromUtf8("name_activator_conc_proc"))
        self.name_cr_conc = QtGui.QLineEdit(self.concentrations)
        self.name_cr_conc.setGeometry(QtCore.QRect(0, 100, 261, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.name_cr_conc.setFont(font)
        self.name_cr_conc.setAlignment(QtCore.Qt.AlignCenter)
        self.name_cr_conc.setObjectName(_fromUtf8("name_cr_conc"))
        self.value_Na_total = QtGui.QDoubleSpinBox(self.concentrations)
        self.value_Na_total.setGeometry(QtCore.QRect(130, 120, 81, 22))
        self.value_Na_total.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Na_total.setAccelerated(True)
        self.value_Na_total.setPrefix(_fromUtf8(""))
        self.value_Na_total.setSuffix(_fromUtf8(""))
        self.value_Na_total.setDecimals(0)
        self.value_Na_total.setMaximum(1e9)
        self.value_Na_total.setSingleStep(1e3)
        self.value_Na_total.setProperty("value", 1e5)
        self.value_Na_total.setObjectName(_fromUtf8("value_Na_total"))
        self.dim_Na_total = QtGui.QLineEdit(self.concentrations)
        self.dim_Na_total.setGeometry(QtCore.QRect(210, 120, 51, 22))
        self.dim_Na_total.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Na_total.setReadOnly(True)
        self.dim_Na_total.setObjectName(_fromUtf8("dim_Na_total"))
        self.name_Ng_total = QtGui.QLineEdit(self.concentrations)
        self.name_Ng_total.setGeometry(QtCore.QRect(40, 20, 91, 22))
        self.name_Ng_total.setAlignment(QtCore.Qt.AlignCenter)
        self.name_Ng_total.setReadOnly(True)
        self.name_Ng_total.setObjectName(_fromUtf8("name_Ng_total"))
        self.name_Na_total = QtGui.QLineEdit(self.concentrations)
        self.name_Na_total.setGeometry(QtCore.QRect(40, 120, 91, 22))
        self.name_Na_total.setAlignment(QtCore.Qt.AlignCenter)
        self.name_Na_total.setReadOnly(True)
        self.name_Na_total.setObjectName(_fromUtf8("name_Na_total"))
        self.name_Ng_total_perc = QtGui.QLineEdit(self.concentrations)
        self.name_Ng_total_perc.setGeometry(QtCore.QRect(42, 70, 111, 22))
        self.name_Ng_total_perc.setObjectName(_fromUtf8("name_Ng_total_perc"))
        self.dim_Ng_total_perc = QtGui.QLineEdit(self.concentrations)
        self.dim_Ng_total_perc.setGeometry(QtCore.QRect(210, 70, 51, 22))
        self.dim_Ng_total_perc.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Ng_total_perc.setReadOnly(True)
        self.dim_Ng_total_perc.setObjectName(_fromUtf8("dim_Ng_total_perc"))
        self.input_parameter.addItem(self.concentrations, _fromUtf8(""))
        self.losses = QtGui.QWidget()
        self.losses.setGeometry(QtCore.QRect(0, 0, 263, 423))
        self.losses.setObjectName(_fromUtf8("losses"))
        self.name_absorbtion_coef = QtGui.QLineEdit(self.losses)
        self.name_absorbtion_coef.setGeometry(QtCore.QRect(0, 0, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_absorbtion_coef.setFont(font)
        self.name_absorbtion_coef.setAlignment(QtCore.Qt.AlignCenter)
        self.name_absorbtion_coef.setReadOnly(True)
        self.name_absorbtion_coef.setObjectName(_fromUtf8("name_absorbtion_coef"))
        self.value_alpha_p = scspin.ScientificDoubleSpinBox(self.losses)
        self.value_alpha_p.setGeometry(QtCore.QRect(140, 20, 71, 22))
        self.value_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.value_alpha_p.setPrefix(_fromUtf8(""))
        self.value_alpha_p.setSuffix(_fromUtf8(""))
        self.value_alpha_p.setDecimals(8)
        self.value_alpha_p.setMaximum(1e-06)
        self.value_alpha_p.setSingleStep(1e-08)
        self.value_alpha_p.setProperty("value", 5e-07)
        self.value_alpha_p.setObjectName(_fromUtf8("value_alpha_p"))
        self.dim_alpha_p = QtGui.QLineEdit(self.losses)
        self.dim_alpha_p.setGeometry(QtCore.QRect(210, 20, 51, 22))
        self.dim_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_alpha_p.setReadOnly(True)
        self.dim_alpha_p.setObjectName(_fromUtf8("dim_alpha_p"))
        self.value_R1 = QtGui.QDoubleSpinBox(self.losses)
        self.value_R1.setGeometry(QtCore.QRect(200, 70, 61, 22))
        self.value_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_R1.setAccelerated(True)
        self.value_R1.setPrefix(_fromUtf8(""))
        self.value_R1.setMaximum(1.0)
        self.value_R1.setSingleStep(0.01)
        self.value_R1.setProperty("value", 1.0)
        self.value_R1.setObjectName(_fromUtf8("value_R1"))
        self.name_input_mirror = QtGui.QLineEdit(self.losses)
        self.name_input_mirror.setGeometry(QtCore.QRect(0, 50, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_input_mirror.setFont(font)
        self.name_input_mirror.setAlignment(QtCore.Qt.AlignCenter)
        self.name_input_mirror.setReadOnly(True)
        self.name_input_mirror.setObjectName(_fromUtf8("name_input_mirror"))
        self.value_R2 = QtGui.QDoubleSpinBox(self.losses)
        self.value_R2.setGeometry(QtCore.QRect(200, 120, 61, 22))
        self.value_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_R2.setAccelerated(True)
        self.value_R2.setPrefix(_fromUtf8(""))
        self.value_R2.setMaximum(1.0)
        self.value_R2.setSingleStep(0.01)
        self.value_R2.setProperty("value", 0.99)
        self.value_R2.setObjectName(_fromUtf8("value_R2"))
        self.name_output_mirror = QtGui.QLineEdit(self.losses)
        self.name_output_mirror.setGeometry(QtCore.QRect(0, 100, 261, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.name_output_mirror.setFont(font)
        self.name_output_mirror.setAlignment(QtCore.Qt.AlignCenter)
        self.name_output_mirror.setReadOnly(True)
        self.name_output_mirror.setObjectName(_fromUtf8("name_output_mirror"))
        self.name_alpha_p = QtGui.QLineEdit(self.losses)
        self.name_alpha_p.setGeometry(QtCore.QRect(60, 20, 81, 22))
        self.name_alpha_p.setAlignment(QtCore.Qt.AlignCenter)
        self.name_alpha_p.setReadOnly(True)
        self.name_alpha_p.setObjectName(_fromUtf8("name_alpha_p"))
        self.name_R1 = QtGui.QLineEdit(self.losses)
        self.name_R1.setGeometry(QtCore.QRect(150, 70, 51, 22))
        self.name_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_R1.setReadOnly(True)
        self.name_R1.setObjectName(_fromUtf8("name_R1"))
        self.name_R2 = QtGui.QLineEdit(self.losses)
        self.name_R2.setGeometry(QtCore.QRect(150, 120, 51, 22))
        self.name_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_R2.setReadOnly(True)
        self.name_R2.setObjectName(_fromUtf8("name_R2"))
        self.input_parameter.addItem(self.losses, _fromUtf8(""))
        self.pumping = QtGui.QWidget()
        self.pumping.setGeometry(QtCore.QRect(0, 0, 263, 423))
        self.pumping.setObjectName(_fromUtf8("pumping"))
        self.name_pump_power = QtGui.QLineEdit(self.pumping)
        self.name_pump_power.setGeometry(QtCore.QRect(0, 10, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_pump_power.setFont(font)
        self.name_pump_power.setAlignment(QtCore.Qt.AlignCenter)
        self.name_pump_power.setReadOnly(True)
        self.name_pump_power.setObjectName(_fromUtf8("name_pump_power"))
        self.value_Pi = QtGui.QDoubleSpinBox(self.pumping)
        self.value_Pi.setGeometry(QtCore.QRect(160, 30, 51, 22))
        self.value_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Pi.setAccelerated(True)
        self.value_Pi.setPrefix(_fromUtf8(""))
        self.value_Pi.setSuffix(_fromUtf8(""))
        self.value_Pi.setMaximum(100.0)
        self.value_Pi.setSingleStep(0.01)
        self.value_Pi.setProperty("value", 0.2)
        self.value_Pi.setObjectName(_fromUtf8("value_Pi"))
        self.value_wavelength = QtGui.QDoubleSpinBox(self.pumping)
        self.value_wavelength.setGeometry(QtCore.QRect(140, 80, 71, 22))
        self.value_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.value_wavelength.setAccelerated(True)
        self.value_wavelength.setPrefix(_fromUtf8(""))
        self.value_wavelength.setSuffix(_fromUtf8(""))
        self.value_wavelength.setDecimals(3)
        self.value_wavelength.setMaximum(5.0)
        self.value_wavelength.setSingleStep(0.001)
        self.value_wavelength.setProperty("value", 0.808)
        self.value_wavelength.setObjectName(_fromUtf8("value_wavelength"))
        self.name_pump_wavelength = QtGui.QLineEdit(self.pumping)
        self.name_pump_wavelength.setGeometry(QtCore.QRect(0, 60, 261, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.name_pump_wavelength.setFont(font)
        self.name_pump_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.name_pump_wavelength.setReadOnly(True)
        self.name_pump_wavelength.setObjectName(_fromUtf8("name_pump_wavelength"))
        self.value_rp = QtGui.QSpinBox(self.pumping)
        self.value_rp.setGeometry(QtCore.QRect(150, 130, 61, 22))
        self.value_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.value_rp.setAccelerated(True)
        self.value_rp.setSuffix(_fromUtf8(""))
        self.value_rp.setPrefix(_fromUtf8(""))
        self.value_rp.setMaximum(1000)
        self.value_rp.setProperty("value", 300)
        self.value_rp.setObjectName(_fromUtf8("value_rp"))
        self.name_pump_radius = QtGui.QLineEdit(self.pumping)
        self.name_pump_radius.setGeometry(QtCore.QRect(0, 110, 261, 22))
        font = QtGui.QFont()
        font.setItalic(True)
        self.name_pump_radius.setFont(font)
        self.name_pump_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.name_pump_radius.setReadOnly(True)
        self.name_pump_radius.setObjectName(_fromUtf8("name_pump_radius"))
        self.dim_Pi = QtGui.QLineEdit(self.pumping)
        self.dim_Pi.setGeometry(QtCore.QRect(210, 30, 51, 22))
        self.dim_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_Pi.setReadOnly(True)
        self.dim_Pi.setObjectName(_fromUtf8("dim_Pi"))
        self.name_Pi = QtGui.QLineEdit(self.pumping)
        self.name_Pi.setGeometry(QtCore.QRect(110, 30, 51, 22))
        self.name_Pi.setAlignment(QtCore.Qt.AlignCenter)
        self.name_Pi.setReadOnly(True)
        self.name_Pi.setObjectName(_fromUtf8("name_Pi"))
        self.name_wavelength = QtGui.QLineEdit(self.pumping)
        self.name_wavelength.setGeometry(QtCore.QRect(40, 80, 101, 22))
        self.name_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.name_wavelength.setReadOnly(True)
        self.name_wavelength.setObjectName(_fromUtf8("name_wavelength"))
        self.dim_wavelength = QtGui.QLineEdit(self.pumping)
        self.dim_wavelength.setGeometry(QtCore.QRect(210, 80, 51, 22))
        self.dim_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_wavelength.setReadOnly(True)
        self.dim_wavelength.setObjectName(_fromUtf8("dim_wavelength"))
        self.dim_rp = QtGui.QLineEdit(self.pumping)
        self.dim_rp.setGeometry(QtCore.QRect(210, 130, 51, 22))
        self.dim_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.dim_rp.setReadOnly(True)
        self.dim_rp.setObjectName(_fromUtf8("dim_rp"))
        self.name_rp = QtGui.QLineEdit(self.pumping)
        self.name_rp.setGeometry(QtCore.QRect(100, 130, 51, 22))
        self.name_rp.setAlignment(QtCore.Qt.AlignCenter)
        self.name_rp.setReadOnly(True)
        self.name_rp.setObjectName(_fromUtf8("name_rp"))
        self.input_parameter.addItem(self.pumping, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.input_parameter, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 2, 2)
        spacerItem6 = QtGui.QSpacerItem(40, 2, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 2, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setMinimumSize(QtCore.QSize(20, 10))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_config = QtGui.QAction(MainWindow)
        self.actionOpen_config.setObjectName(_fromUtf8("actionOpen_config"))
        self.actionSave_config = QtGui.QAction(MainWindow)
        self.actionSave_config.setObjectName(_fromUtf8("actionSave_config"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionExpand = QtGui.QAction(MainWindow)
        self.actionExpand.setObjectName(_fromUtf8("actionExpand"))
        self.actionCalculate = QtGui.QAction(MainWindow)
        self.actionCalculate.setObjectName(_fromUtf8("actionCalculate"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionOpen_config)
        self.menuFile.addAction(self.actionSave_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionExpand)
        self.menuRun.addAction(self.actionCalculate)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.input_parameter.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.button_quit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.actionExpand, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.showMaximized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.button_quit.setText(_translate("MainWindow", "Quit", None))
        self.button_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.input_title.setText(_translate("MainWindow", "Input Parameters", None))
        self.button_calculate.setText(_translate("MainWindow", "Calculate", None))
        self.name1_times.setText(_translate("MainWindow", "Lifetime of high laser level", None))
        self.name2_times.setText(_translate("MainWindow", "Lifetime of Cr(4+) excited level", None))
        self.name1_calc_time.setText(_translate("MainWindow", "Calculation time", None))
        self.name1_time_step.setText(_translate("MainWindow", "Time spem in calculations", None))
        self.name_tau_m.setText(_translate("MainWindow", "tau_m = ", None))
        self.dim_tau_m.setText(_translate("MainWindow", " μs", None))
        self.dim_dt.setText(_translate("MainWindow", " μs", None))
        self.ldim_tau_g.setText(_translate("MainWindow", " μs", None))
        self.dim_tau_a.setText(_translate("MainWindow", " μs", None))
        self.name_dt.setText(_translate("MainWindow", "dt = ", None))
        self.name_tau_g.setText(_translate("MainWindow", "tau_g = ", None))
        self.name_tau_a.setText(_translate("MainWindow", "tau_a = ", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.times), _translate("MainWindow", "Times", None))
        self.name_active_medium.setText(_translate("MainWindow", "Thickness of active medium", None))
        self.name_absorber.setText(_translate("MainWindow", "Absorber thickness", None))
        self.name_beam_radius.setText(_translate("MainWindow", "Laser beam radius", None))
        self.name_index.setText(_translate("MainWindow", "YAG:Nd refractive index at 1.064 um", None))
        self.dim_lg.setText(_translate("MainWindow", " μm", None))
        self.dim_la.setText(_translate("MainWindow", " μm", None))
        self.dim_rl.setText(_translate("MainWindow", " μm", None))
        self.name_lg.setText(_translate("MainWindow", "lg = ", None))
        self.name_la.setText(_translate("MainWindow", "la = ", None))
        self.name_rl.setText(_translate("MainWindow", "rl = ", None))
        self.name_n.setText(_translate("MainWindow", "n = ", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.dimensions), _translate("MainWindow", "Dimensions", None))
        self.name_laser_trans.setText(_translate("MainWindow", " Efficient cross-section of laser transition", None))
        self.dim_sigma_g.setText(_translate("MainWindow", "μm^2", None))
        self.dim_sigma_a1.setText(_translate("MainWindow", "μm^2", None))
        self.name_absorber_levels_1.setText(_translate("MainWindow", "Cross-section  between Cr(4+) levels", None))
        self.dim_sigma_a2.setText(_translate("MainWindow", "μm^2", None))
        self.name_absorber_levels_2.setText(_translate("MainWindow", "Cross-section  between Cr(4+) levels", None))
        self.name_sigma_g.setText(_translate("MainWindow", "sigma_g = ", None))
        self.name_sigma_a1.setText(_translate("MainWindow", "sigma_a1 = ", None))
        self.name_sigma_a2.setText(_translate("MainWindow", "sigma_a2 = ", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.crosssections), _translate("MainWindow", "Cross-sections", None))
        self.name_activator_conc.setText(_translate("MainWindow", "Activator concentration", None))
        self.dim_Ng_total.setText(_translate("MainWindow", "μm^-3", None))
        self.name_activator_conc_proc.setText(_translate("MainWindow", "Activator concentration at %", None))
        self.name_cr_conc.setText(_translate("MainWindow", "Cr(4+) ion concentration", None))
        self.dim_Na_total.setText(_translate("MainWindow", "μm^-3", None))
        self.name_Ng_total.setText(_translate("MainWindow", "Ng_total = ", None))
        self.name_Na_total.setText(_translate("MainWindow", "Na_total = ", None))
        self.name_Ng_total_perc.setText(_translate("MainWindow", "Ng total_perc =", None))
        self.dim_Ng_total_perc.setText(_translate("MainWindow", "%", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.concentrations), _translate("MainWindow", "Concentrations", None))
        self.name_absorbtion_coef.setText(_translate("MainWindow", "Absorption coefficient on a wavelength", None))
        self.dim_alpha_p.setText(_translate("MainWindow", "1/μm", None))
        self.name_input_mirror.setText(_translate("MainWindow", "Reflectivity of input mirror", None))
        self.name_output_mirror.setText(_translate("MainWindow", "Reflectivity of output mirror", None))
        self.name_alpha_p.setText(_translate("MainWindow", "alpha_p = ", None))
        self.name_R1.setText(_translate("MainWindow", "R1 = ", None))
        self.name_R2.setText(_translate("MainWindow", "R2 =", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.losses), _translate("MainWindow", "Losses", None))
        self.name_pump_power.setText(_translate("MainWindow", "Pumping power", None))
        self.name_pump_wavelength.setText(_translate("MainWindow", "Pumping wavelength", None))
        self.name_pump_radius.setText(_translate("MainWindow", "Pumping beam radius", None))
        self.dim_Pi.setText(_translate("MainWindow", "W", None))
        self.name_Pi.setText(_translate("MainWindow", "Pi =", None))
        self.name_wavelength.setText(_translate("MainWindow", "wavelength =", None))
        self.dim_wavelength.setText(_translate("MainWindow", "μm", None))
        self.dim_rp.setText(_translate("MainWindow", "μm", None))
        self.name_rp.setText(_translate("MainWindow", "rp =", None))
        self.input_parameter.setItemText(self.input_parameter.indexOf(self.pumping), _translate("MainWindow", "Pumping", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_config.setText(_translate("MainWindow", "Open config", None))
        self.actionOpen_config.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave_config.setText(_translate("MainWindow", "Save config", None))
        self.actionSave_config.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionExpand.setText(_translate("MainWindow", "Expand", None))
        self.actionExpand.setShortcut(_translate("MainWindow", "Ctrl+F, Ctrl+S", None))
        self.actionCalculate.setText(_translate("MainWindow", "Calculate", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

